itemAssetsList = {
    "Acacia Leaves" : "Assets\\Items\\acacia_leaves.png",
    "Acacia Log" : "Assets\\Items\\acacia_log.png",
    "Acacia Planks" : "Assets\\Items\\acacia_planks.png",
    "Acacia Sapling" : "Assets\\Items\\acacia_sapling.png",
    "Acacia Slab" : "Assets\\Items\\acacia_slab.png",
    "Acacia Stairs" : "Assets\\Items\\acacia_stairs.png",
    "Acacia Wood" : "Assets\\Items\\acacia_wood.png",
    "Allium" : "Assets\\Items\\allium.png",
    "Ancient Debris" : "Assets\\Items\\ancient_debris.png",
    "Andesite" : "Assets\\Items\\andesite.png",
    "Andesite Slab" : "Assets\\Items\\andesite_slab.png",
    "Andesite Stairs" : "Assets\\Items\\andesite_stairs.png",
    "Azure Bluet" : "Assets\\Items\\azure_bluet.png",
    "Basalt" : "Assets\\Items\\basalt.png",
    "Bedrock" : "Assets\\Items\\bedrock.png",
    "Birch Leaves" : "Assets\\Items\\birch_leaves.png",
    "Birch Log" : "Assets\\Items\\birch_log.png",
    "Birch Planks" : "Assets\\Items\\birch_planks.png",
    "Birch Sapling" : "Assets\\Items\\birch_sapling.png",
    "Birch Slab" : "Assets\\Items\\birch_slab.png",
    "Birch Stairs" : "Assets\\Items\\birch_stairs.png",
    "Birch Wood" : "Assets\\Items\\birch_wood.png",
    "Blackstone" : "Assets\\Items\\blackstone.png",
    "Blackstone Slab" : "Assets\\Items\\blackstone_slab.png",
    "Blackstone Stairs" : "Assets\\Items\\blackstone_stairs.png",
    "Black Concrete" : "Assets\\Items\\black_concrete.png",
    "Black Concrete Powder" : "Assets\\Items\\black_concrete_powder.png",
    "Black Stained Glass" : "Assets\\Items\\black_stained_glass.png",
    "Black Terracotta" : "Assets\\Items\\black_terracotta.png",
    "Black Wool" : "Assets\\Items\\black_wool.png",
    "Block Of Coal" : "Assets\\Items\\block_of_coal.png",
    "Block Of Diamond" : "Assets\\Items\\block_of_diamond.png",
    "Block Of Emerald" : "Assets\\Items\\block_of_emerald.png",
    "Block Of Gold" : "Assets\\Items\\block_of_gold.png",
    "Block Of Iron" : "Assets\\Items\\block_of_iron.png",
    "Block Of Netherite" : "Assets\\Items\\block_of_netherite.png",
    "Block Of Quartz" : "Assets\\Items\\block_of_quartz.png",
    "Blue Concrete" : "Assets\\Items\\blue_concrete.png",
    "Blue Concrete Powder" : "Assets\\Items\\blue_concrete_powder.png",
    "Blue Ice" : "Assets\\Items\\blue_ice.png",
    "Blue Orchid" : "Assets\\Items\\blue_orchid.png",
    "Blue Stained Glass" : "Assets\\Items\\blue_stained_glass.png",
    "Blue Terracotta" : "Assets\\Items\\blue_terracotta.png",
    "Blue Wool" : "Assets\\Items\\blue_wool.png",
    "Bone Block" : "Assets\\Items\\bone_block.png",
    "Bookshelf" : "Assets\\Items\\bookshelf.png",
    "Brain Coral Block" : "Assets\\Items\\brain_coral_block.png",
    "Bricks" : "Assets\\Items\\bricks.png",
    "Brick Slab" : "Assets\\Items\\brick_slab.png",
    "Brick Stairs" : "Assets\\Items\\brick_stairs.png",
    "Brown Concrete" : "Assets\\Items\\brown_concrete.png",
    "Brown Concrete Powder" : "Assets\\Items\\brown_concrete_powder.png",
    "Brown Stained Glass" : "Assets\\Items\\brown_stained_glass.png",
    "Brown Terracotta" : "Assets\\Items\\brown_terracotta.png",
    "Brown Wool" : "Assets\\Items\\brown_wool.png",
    "Bubble Coral Block" : "Assets\\Items\\bubble_coral_block.png",
    "Carved Pumpkin" : "Assets\\Items\\carved_pumpkin.png",
    "Chiseled Nether Bricks" : "Assets\\Items\\chiseled_nether_bricks.png",
    "Chiseled Polished Blackstone" : "Assets\\Items\\chiseled_polished_blackstone.png",
    "Chiseled Quartz Block" : "Assets\\Items\\chiseled_quartz_block.png",
    "Chiseled Red Sandstone" : "Assets\\Items\\chiseled_red_sandstone.png",
    "Chiseled Sandstone" : "Assets\\Items\\chiseled_sandstone.png",
    "Chiseled Stone Bricks" : "Assets\\Items\\chiseled_stone_bricks.png",
    "Clay" : "Assets\\Items\\clay.png",
    "Coal Ore" : "Assets\\Items\\coal_ore.png",
    "Coarse Dirt" : "Assets\\Items\\coarse_dirt.png",
    "Cobblestone" : "Assets\\Items\\cobblestone.png",
    "Cobblestone Slab" : "Assets\\Items\\cobblestone_slab.png",
    "Cobblestone Stairs" : "Assets\\Items\\cobblestone_stairs.png",
    "Cobweb" : "Assets\\Items\\cobweb.png",
    "Cornflower" : "Assets\\Items\\cornflower.png",
    "Cracked Nether Bricks" : "Assets\\Items\\cracked_nether_bricks.png",
    "Cracked Polished Blackstone Bricks" : "Assets\\Items\\cracked_polished_blackstone_bricks.png",
    "Cracked Stone Bricks" : "Assets\\Items\\cracked_stone_bricks.png",
    "Crimson Hyphae" : "Assets\\Items\\crimson_hyphae.gif",
    "Crimson Nylium" : "Assets\\Items\\crimson_nylium.png",
    "Crimson Planks" : "Assets\\Items\\crimson_planks.png",
    "Crimson Slab" : "Assets\\Items\\crimson_slab.png",
    "Crimson Stairs" : "Assets\\Items\\crimson_stairs.png",
    "Crimson Stem" : "Assets\\Items\\crimson_stem.gif",
    "Crying Obsidian" : "Assets\\Items\\crying_obsidian.png",
    "Cut Red Sandstone" : "Assets\\Items\\cut_red_sandstone.png",
    "Cut Red Sandstone Slab" : "Assets\\Items\\cut_red_sandstone_slab.png",
    "Cut Sandstone" : "Assets\\Items\\cut_sandstone.png",
    "Cut Sandstone Slab" : "Assets\\Items\\cut_sandstone_slab.png",
    "Cyan Concrete" : "Assets\\Items\\cyan_concrete.png",
    "Cyan Concrete Powder" : "Assets\\Items\\cyan_concrete_powder.png",
    "Cyan Stained Glass" : "Assets\\Items\\cyan_stained_glass.png",
    "Cyan Terracotta" : "Assets\\Items\\cyan_terracotta.png",
    "Cyan Wool" : "Assets\\Items\\cyan_wool.png",
    "Dandelion" : "Assets\\Items\\dandelion.png",
    "Dark Oak" : "Assets\\Items\\dark_oak.png",
    "Dark Oak Leaves" : "Assets\\Items\\dark_oak_leaves.png",
    "Dark Oak Log" : "Assets\\Items\\dark_oak_log.png",
    "Dark Oak Planks" : "Assets\\Items\\dark_oak_planks.png",
    "Dark Oak Sapling" : "Assets\\Items\\dark_oak_sapling.png",
    "Dark Oak Slab" : "Assets\\Items\\dark_oak_slab.png",
    "Dark Oak Stairs" : "Assets\\Items\\dark_oak_stairs.png",
    "Dark Oak Wood" : "Assets\\Items\\dark_oak_wood.png",
    "Dark Prismarine" : "Assets\\Items\\dark_prismarine.png",
    "Dark Prismarine Slab" : "Assets\\Items\\dark_prismarine_slab.png",
    "Dark Prismarine Stairs" : "Assets\\Items\\dark_prismarine_stairs.png",
    "Dead Brain Coral Block" : "Assets\\Items\\dead_brain_coral_block.png",
    "Dead Bubble Coral Block" : "Assets\\Items\\dead_bubble_coral_block.png",
    "Dead Bush" : "Assets\\Items\\dead_bush.png",
    "Dead Fire Coral Block" : "Assets\\Items\\dead_fire_coral_block.png",
    "Dead Horn Coral Block" : "Assets\\Items\\dead_horn_coral_block.png",
    "Dead Tube Coral Block" : "Assets\\Items\\dead_tube_coral_block.png",
    "Diamond Ore" : "Assets\\Items\\diamond_ore.png",
    "Diorite" : "Assets\\Items\\diorite.png",
    "Diorite Slab" : "Assets\\Items\\diorite_slab.png",
    "Diorite Stairs" : "Assets\\Items\\diorite_stairs.png",
    "Dirt" : "Assets\\Items\\dirt.png",
    "Dried Kelp Block" : "Assets\\Items\\dried_kelp_block.png",
    "Emerald Ore" : "Assets\\Items\\emerald_ore.png",
    "End Stone" : "Assets\\Items\\end_stone.png",
    "End Stone Bricks" : "Assets\\Items\\end_stone_bricks.png",
    "End Stone Brick Slab" : "Assets\\Items\\end_stone_brick_slab.png",
    "End Stone Brick Stairs" : "Assets\\Items\\end_stone_brick_stairs.png",
    "Fern" : "Assets\\Items\\fern.png",
    "Fire Coral Block" : "Assets\\Items\\fire_coral_block.png",
    "Gilded Blackstone" : "Assets\\Items\\gilded_blackstone.png",
    "Glass" : "Assets\\Items\\glass.png",
    "Glowstone" : "Assets\\Items\\glowstone.png",
    "Gold Ore" : "Assets\\Items\\gold_ore.png",
    "Granite" : "Assets\\Items\\granite.png",
    "Granite Slab" : "Assets\\Items\\granite_slab.png",
    "Granite Stairs" : "Assets\\Items\\granite_stairs.png",
    "Grass" : "Assets\\Items\\grass.png",
    "Grass Block" : "Assets\\Items\\grass_block.png",
    "Gravel" : "Assets\\Items\\gravel.png",
    "Gray Concrete" : "Assets\\Items\\gray_concrete.png",
    "Gray Concrete Powder" : "Assets\\Items\\gray_concrete_powder.png",
    "Gray Stained Glass" : "Assets\\Items\\gray_stained_glass.png",
    "Gray Terracotta" : "Assets\\Items\\gray_terracotta.png",
    "Gray Wool" : "Assets\\Items\\gray_wool.png",
    "Green Concrete" : "Assets\\Items\\green_concrete.png",
    "Green Concrete Powder" : "Assets\\Items\\green_concrete_powder.png",
    "Green Stained Glass" : "Assets\\Items\\green_stained_glass.png",
    "Green Terracotta" : "Assets\\Items\\green_terracotta.png",
    "Green Wool" : "Assets\\Items\\green_wool.png",
    "Hay Bale" : "Assets\\Items\\hay_bale.png",
    "Horn Coral Block" : "Assets\\Items\\horn_coral_block.png",
    "Ice" : "Assets\\Items\\ice.png",
    "Iron Ore" : "Assets\\Items\\iron_ore.png",
    "Jack O'Lantern" : "Assets\\Items\\jack_o'lantern.png",
    "Jungle Leaves" : "Assets\\Items\\jungle_leaves.png",
    "Jungle Log" : "Assets\\Items\\jungle_log.png",
    "Jungle Planks" : "Assets\\Items\\jungle_planks.png",
    "Jungle Sapling" : "Assets\\Items\\jungle_sapling.png",
    "Jungle Slab" : "Assets\\Items\\jungle_slab.png",
    "Jungle Stairs" : "Assets\\Items\\jungle_stairs.png",
    "Jungle Wood" : "Assets\\Items\\jungle_wood.png",
    "Lapis Lazuli Block" : "Assets\\Items\\lapis_lazuli_block.png",
    "Lapis Lazuli Ore" : "Assets\\Items\\lapis_lazuli_ore.png",
    "Light Blue Concrete" : "Assets\\Items\\light_blue_concrete.png",
    "Light Blue Concrete Powder" : "Assets\\Items\\light_blue_concrete_powder.png",
    "Light Blue Stained Glass" : "Assets\\Items\\light_blue_stained_glass.png",
    "Light Blue Terracotta" : "Assets\\Items\\light_blue_terracotta.png",
    "Light Blue Wool" : "Assets\\Items\\light_blue_wool.png",
    "Light Gray Concrete" : "Assets\\Items\\light_gray_concrete.png",
    "Light Gray Concrete Powder" : "Assets\\Items\\light_gray_concrete_powder.png",
    "Light Gray Stained Glass" : "Assets\\Items\\light_gray_stained_glass.png",
    "Light Gray Terracotta" : "Assets\\Items\\light_gray_terracotta.png",
    "Light Gray Wool" : "Assets\\Items\\light_gray_wool.png",
    "Lilac" : "Assets\\Items\\lilac.png",
    "Lily Of The Valley" : "Assets\\Items\\lily_of_the_valley.png",
    "Lime Concrete" : "Assets\\Items\\lime_concrete.png",
    "Lime Concrete Powder" : "Assets\\Items\\lime_concrete_powder.png",
    "Lime Stained Glass" : "Assets\\Items\\lime_stained_glass.png",
    "Lime Terracotta" : "Assets\\Items\\lime_terracotta.png",
    "Lime Wool" : "Assets\\Items\\lime_wool.png",
    "Magenta Concrete" : "Assets\\Items\\magenta_concrete.png",
    "Magenta Concrete Powder" : "Assets\\Items\\magenta_concrete_powder.png",
    "Magenta Stained Glass" : "Assets\\Items\\magenta_stained_glass.png",
    "Magenta Terracotta" : "Assets\\Items\\magenta_terracotta.png",
    "Magenta Wool" : "Assets\\Items\\magenta_wool.png",
    "Magma Block" : "Assets\\Items\\magma_block.gif",
    "Melon" : "Assets\\Items\\melon.png",
    "Mossy Cobblestone" : "Assets\\Items\\mossy_cobblestone.png",
    "Mossy Cobblestone Slab" : "Assets\\Items\\mossy_cobblestone_slab.png",
    "Mossy Cobblestone Stairs" : "Assets\\Items\\mossy_cobblestone_stairs.png",
    "Mossy Stone Bricks" : "Assets\\Items\\mossy_stone_bricks.png",
    "Mossy Stone Brick Slab" : "Assets\\Items\\mossy_stone_brick_slab.png",
    "Mossy Stone Brick Stairs" : "Assets\\Items\\mossy_stone_brick_stairs.png",
    "Mycelium" : "Assets\\Items\\mycelium.png",
    "Netherrack" : "Assets\\Items\\netherrack.png",
    "Nether Bricks" : "Assets\\Items\\nether_bricks.png",
    "Nether Brick Slab" : "Assets\\Items\\nether_brick_slab.png",
    "Nether Brick Stairs" : "Assets\\Items\\nether_brick_stairs.png",
    "Nether Gold Ore" : "Assets\\Items\\nether_gold_ore.png",
    "Nether Quartz Ore" : "Assets\\Items\\nether_quartz_ore.png",
    "Nether Wart Block" : "Assets\\Items\\nether_wart_block.png",
    "Oak Leaves" : "Assets\\Items\\oak_leaves.png",
    "Oak Log" : "Assets\\Items\\oak_log.png",
    "Oak Planks" : "Assets\\Items\\oak_planks.png",
    "Oak Sapling" : "Assets\\Items\\oak_sapling.png",
    "Oak Slab" : "Assets\\Items\\oak_slab.png",
    "Oak Stairs" : "Assets\\Items\\oak_stairs.png",
    "Oak Wood" : "Assets\\Items\\oak_wood.png",
    "Obsidian" : "Assets\\Items\\obsidian.png",
    "Orange Concrete" : "Assets\\Items\\orange_concrete.png",
    "Orange Concrete Powder" : "Assets\\Items\\orange_concrete_powder.png",
    "Orange Stained Glass" : "Assets\\Items\\orange_stained_glass.png",
    "Orange Terracotta" : "Assets\\Items\\orange_terracotta.png",
    "Orange Tulip" : "Assets\\Items\\orange_tulip.png",
    "Orange Wool" : "Assets\\Items\\orange_wool.png",
    "Oxeye Daisy" : "Assets\\Items\\oxeye_daisy.png",
    "Packed Ice" : "Assets\\Items\\packed_ice.png",
    "Peony" : "Assets\\Items\\peony.png",
    "Pink Concrete" : "Assets\\Items\\pink_concrete.png",
    "Pink Concrete Powder" : "Assets\\Items\\pink_concrete_powder.png",
    "Pink Stained Glass" : "Assets\\Items\\pink_stained_glass.png",
    "Pink Terracotta" : "Assets\\Items\\pink_terracotta.png",
    "Pink Tulip" : "Assets\\Items\\pink_tulip.png",
    "Pink Wool" : "Assets\\Items\\pink_wool.png",
    "Podzol" : "Assets\\Items\\podzol.png",
    "Polished Andesite" : "Assets\\Items\\polished_andesite.png",
    "Polished Andesite Slab" : "Assets\\Items\\polished_andesite_slab.png",
    "Polished Andesite Stairs" : "Assets\\Items\\polished_andesite_stairs.png",
    "Polished Basalt" : "Assets\\Items\\polished_basalt.png",
    "Polished Blackstone" : "Assets\\Items\\polished_blackstone.png",
    "Polished Blackstone Bricks" : "Assets\\Items\\polished_blackstone_bricks.png",
    "Polished Blackstone Brick Slab" : "Assets\\Items\\polished_blackstone_brick_slab.png",
    "Polished Blackstone Brick Stairs" : "Assets\\Items\\polished_blackstone_brick_stairs.png",
    "Polished Blackstone Slab" : "Assets\\Items\\polished_blackstone_slab.png",
    "Polished Blackstone Stairs" : "Assets\\Items\\polished_blackstone_stairs.png",
    "Polished Diorite" : "Assets\\Items\\polished_diorite.png",
    "Polished Diorite Slab" : "Assets\\Items\\polished_diorite_slab.png",
    "Polished Diorite Stairs" : "Assets\\Items\\polished_diorite_stairs.png",
    "Polished Granite" : "Assets\\Items\\polished_granite.png",
    "Polished Granite Slab" : "Assets\\Items\\polished_granite_slab.png",
    "Polished Granite Stairs" : "Assets\\Items\\polished_granite_stairs.png",
    "Poppy" : "Assets\\Items\\poppy.png",
    "Prismarine" : "Assets\\Items\\prismarine.gif",
    "Prismarine Bricks" : "Assets\\Items\\prismarine_bricks.png",
    "Prismarine Brick Slab" : "Assets\\Items\\prismarine_brick_slab.png",
    "Prismarine Brick Stairs" : "Assets\\Items\\prismarine_brick_stairs.png",
    "Prismarine Slab" : "Assets\\Items\\prismarine_slab.png",
    "Prismarine Stairs" : "Assets\\Items\\prismarine_stairs.gif",
    "Pumpkin" : "Assets\\Items\\pumpkin.png",
    "Purple Concrete" : "Assets\\Items\\purple_concrete.png",
    "Purple Concrete Powder" : "Assets\\Items\\purple_concrete_powder.png",
    "Purple Stained Glass" : "Assets\\Items\\purple_stained_glass.png",
    "Purple Terracotta" : "Assets\\Items\\purple_terracotta.png",
    "Purple Wool" : "Assets\\Items\\purple_wool.png",
    "Purpur Block" : "Assets\\Items\\purpur_block.png",
    "Purpur Pillar" : "Assets\\Items\\purpur_pillar.png",
    "Purpur Slab" : "Assets\\Items\\purpur_slab.png",
    "Purpur Stairs" : "Assets\\Items\\purpur_stairs.png",
    "Quartz Bricks" : "Assets\\Items\\quartz_bricks.png",
    "Quartz Pillar" : "Assets\\Items\\quartz_pillar.png",
    "Quartz Slab" : "Assets\\Items\\quartz_slab.png",
    "Quartz Stairs" : "Assets\\Items\\quartz_stairs.png",
    "Redstone Ore" : "Assets\\Items\\redstone_ore.png",
    "Red Concrete" : "Assets\\Items\\red_concrete.png",
    "Red Concrete Powder" : "Assets\\Items\\red_concrete_powder.png",
    "Red Nether Bricks" : "Assets\\Items\\red_nether_bricks.png",
    "Red Nether Brick Slab" : "Assets\\Items\\red_nether_brick_slab.png",
    "Red Nether Brick Stairs" : "Assets\\Items\\red_nether_brick_stairs.png",
    "Red Sand" : "Assets\\Items\\red_sand.png",
    "Red Sandstone" : "Assets\\Items\\red_sandstone.png",
    "Red Sandstone Slab" : "Assets\\Items\\red_sandstone_slab.png",
    "Red Sandstone Stairs" : "Assets\\Items\\red_sandstone_stairs.png",
    "Red Stained Glass" : "Assets\\Items\\red_stained_glass.png",
    "Red Terracotta" : "Assets\\Items\\red_terracotta.png",
    "Red Tulip" : "Assets\\Items\\red_tulip.png",
    "Red Wool" : "Assets\\Items\\red_wool.png",
    "Rose Bush" : "Assets\\Items\\rose_bush.png",
    "Sand" : "Assets\\Items\\sand.png",
    "Sandstone" : "Assets\\Items\\sandstone.png",
    "Sandstone Slab" : "Assets\\Items\\sandstone_slab.png",
    "Sandstone Stairs" : "Assets\\Items\\sandstone_stairs.png",
    "Seagrass" : "Assets\\Items\\seagrass.gif",
    "Sea Lantern" : "Assets\\Items\\sea_lantern.gif",
    "Sea Pickle" : "Assets\\Items\\sea_pickle.png",
    "Smooth Quartz Block" : "Assets\\Items\\smooth_quartz_block.png",
    "Smooth Quartz Slab" : "Assets\\Items\\smooth_quartz_slab.png",
    "Smooth Quartz Stairs" : "Assets\\Items\\smooth_quartz_stairs.png",
    "Smooth Red Sandstone" : "Assets\\Items\\smooth_red_sandstone.png",
    "Smooth Red Sandstone Slab" : "Assets\\Items\\smooth_red_sandstone_slab.png",
    "Smooth Red Sandstone Stairs" : "Assets\\Items\\smooth_red_sandstone_stairs.png",
    "Smooth Sandstone" : "Assets\\Items\\smooth_sandstone.png",
    "Smooth Sandstone Slab" : "Assets\\Items\\smooth_sandstone_slab.png",
    "Smooth Sandstone Stairs" : "Assets\\Items\\smooth_sandstone_stairs.png",
    "Smooth Stone" : "Assets\\Items\\smooth_stone.png",
    "Smooth Stone Slab" : "Assets\\Items\\smooth_stone_slab.png",
    "Snow Block" : "Assets\\Items\\snow_block.png",
    "Soul Sand" : "Assets\\Items\\soul_sand.png",
    "Soul Soil" : "Assets\\Items\\soul_soil.png",
    "Sponge" : "Assets\\Items\\sponge.png",
    "Spruce Leaves" : "Assets\\Items\\spruce_leaves.png",
    "Spruce Log" : "Assets\\Items\\spruce_log.png",
    "Spruce Planks" : "Assets\\Items\\spruce_planks.png",
    "Spruce Sapling" : "Assets\\Items\\spruce_sapling.png",
    "Spruce Slab" : "Assets\\Items\\spruce_slab.png",
    "Spruce Stairs" : "Assets\\Items\\spruce_stairs.png",
    "Spruce Wood" : "Assets\\Items\\spruce_wood.png",
    "Stone" : "Assets\\Items\\stone.png",
    "Stone Bricks" : "Assets\\Items\\stone_bricks.png",
    "Stone Brick Slab" : "Assets\\Items\\stone_brick_slab.png",
    "Stone Brick Stairs" : "Assets\\Items\\stone_brick_stairs.png",
    "Stone Slab" : "Assets\\Items\\stone_slab.png",
    "Stone Stairs" : "Assets\\Items\\stone_stairs.png",
    "Stripped Acacia Log" : "Assets\\Items\\stripped_acacia_log.png",
    "Stripped Acacia Wood" : "Assets\\Items\\stripped_acacia_wood.png",
    "Stripped Birch Log" : "Assets\\Items\\stripped_birch_log.png",
    "Stripped Birch Wood" : "Assets\\Items\\stripped_birch_wood.png",
    "Stripped Crimson Hyphae" : "Assets\\Items\\stripped_crimson_hyphae.png",
    "Stripped Crimson Stem" : "Assets\\Items\\stripped_crimson_stem.png",
    "Stripped Dark Oak Log" : "Assets\\Items\\stripped_dark_oak_log.png",
    "Stripped Dark Oak Wood" : "Assets\\Items\\stripped_dark_oak_wood.png",
    "Stripped Jungle Log" : "Assets\\Items\\stripped_jungle_log.png",
    "Stripped Jungle Wood" : "Assets\\Items\\stripped_jungle_wood.png",
    "Stripped Oak Log" : "Assets\\Items\\stripped_oak_log.png",
    "Stripped Oak Wood" : "Assets\\Items\\stripped_oak_wood.png",
    "Stripped Spruce Log" : "Assets\\Items\\stripped_spruce_log.png",
    "Stripped Spruce Wood" : "Assets\\Items\\stripped_spruce_wood.png",
    "Stripped Warped Hyphae" : "Assets\\Items\\stripped_warped_hyphae.png",
    "Stripped Warped Stem" : "Assets\\Items\\stripped_warped_stem.png",
    "Sunflower" : "Assets\\Items\\sunflower.png",
    "Terracotta" : "Assets\\Items\\terracotta.png",
    "Tube Coral Block" : "Assets\\Items\\tube_coral_block.png",
    "Warped Hyphae" : "Assets\\Items\\warped_hyphae.gif",
    "Warped Nylium" : "Assets\\Items\\warped_nylium.png",
    "Warped Planks" : "Assets\\Items\\warped_planks.png",
    "Warped Slab" : "Assets\\Items\\warped_slab.png",
    "Warped Stairs" : "Assets\\Items\\warped_stairs.png",
    "Warped Stem" : "Assets\\Items\\warped_stem.gif",
    "Warped Wart Block" : "Assets\\Items\\warped_wart_block.png",
    "Wet Sponge" : "Assets\\Items\\wet_sponge.png",
    "White Concrete" : "Assets\\Items\\white_concrete.png",
    "White Concrete Powder" : "Assets\\Items\\white_concrete_powder.png",
    "White Stained Glass" : "Assets\\Items\\white_stained_glass.png",
    "White Terracotta" : "Assets\\Items\\white_terracotta.png",
    "White Tulip" : "Assets\\Items\\white_tulip.png",
    "White Wool" : "Assets\\Items\\white_wool.png",
    "Wither Rose" : "Assets\\Items\\wither_rose.png",
    "Yellow Concrete" : "Assets\\Items\\yellow_concrete.png",
    "Yellow Concrete Powder" : "Assets\\Items\\yellow_concrete_powder.png",
    "Yellow Stained Glass" : "Assets\\Items\\yellow_stained_glass.png",
    "Yellow Terracotta" : "Assets\\Items\\yellow_terracotta.png",
    "Yellow Wool" : "Assets\\Items\\yellow_wool.png",
}
