itemAssetsList = {
    "Acacia Boat" : "Assets\\Items\\acacia_boat.png",
    "Acacia Button" : "Assets\\Items\\acacia_button.png",
    "Acacia Door" : "Assets\\Items\\acacia_door.png",
    "Acacia Fence" : "Assets\\Items\\acacia_fence.png",
    "Acacia Fence Gate" : "Assets\\Items\\acacia_fence_gate.png",
    "Acacia Leaves" : "Assets\\Items\\acacia_leaves.png",
    "Acacia Log" : "Assets\\Items\\acacia_log.png",
    "Acacia Planks" : "Assets\\Items\\acacia_planks.png",
    "Acacia Pressure Plate" : "Assets\\Items\\acacia_pressure_plate.png",
    "Acacia Sapling" : "Assets\\Items\\acacia_sapling.png",
    "Acacia Sign" : "Assets\\Items\\acacia_sign.png",
    "Acacia Slab" : "Assets\\Items\\acacia_slab.png",
    "Acacia Stairs" : "Assets\\Items\\acacia_stairs.png",
    "Acacia Trapdoor" : "Assets\\Items\\acacia_trapdoor.png",
    "Acacia Wood" : "Assets\\Items\\acacia_wood.png",
    "Activator Rail" : "Assets\\Items\\activator_rail.png",
    "Allium" : "Assets\\Items\\allium.png",
    "Ancient Debris" : "Assets\\Items\\ancient_debris.png",
    "Andesite" : "Assets\\Items\\andesite.png",
    "Andesite Slab" : "Assets\\Items\\andesite_slab.png",
    "Andesite Stairs" : "Assets\\Items\\andesite_stairs.png",
    "Andesite Wall" : "Assets\\Items\\andesite_wall.png",
    "Anvil" : "Assets\\Items\\anvil.png",
    "Apple" : "Assets\\Items\\apple.png",
    "Armor Stand" : "Assets\\Items\\armor_stand.png",
    "Arrow" : "Assets\\Items\\arrow.png",
    "Arrow of Fire Resistance" : "Assets\\Items\\arrow_of_fire_resistance.png",
    "Arrow of Harming" : "Assets\\Items\\arrow_of_harming.png",
    "Arrow of Healing" : "Assets\\Items\\arrow_of_healing.png",
    "Arrow of Invisibility" : "Assets\\Items\\arrow_of_invisibility.png",
    "Arrow of Leaping" : "Assets\\Items\\arrow_of_leaping.png",
    "Arrow of Long Fire Resistance" : "Assets\\Items\\arrow_of_long_fire_resistance.png",
    "Arrow of Long Invisibility" : "Assets\\Items\\arrow_of_long_invisibility.png",
    "Arrow of Long Leaping" : "Assets\\Items\\arrow_of_long_leaping.png",
    "Arrow of Long Night Vision" : "Assets\\Items\\arrow_of_long_night_vision.png",
    "Arrow of Long Poison" : "Assets\\Items\\arrow_of_long_poison.png",
    "Arrow of Long Regeneration" : "Assets\\Items\\arrow_of_long_regeneration.png",
    "Arrow of Long Slowness" : "Assets\\Items\\arrow_of_long_slowness.png",
    "Arrow of Long Slow Falling" : "Assets\\Items\\arrow_of_long_slow_falling.png",
    "Arrow of Long Strength" : "Assets\\Items\\arrow_of_long_strength.png",
    "Arrow of Long Swiftness" : "Assets\\Items\\arrow_of_long_swiftness.png",
    "Arrow of Long Turtle Master" : "Assets\\Items\\arrow_of_long_turtle_master.png",
    "Arrow of Long Water Breathing" : "Assets\\Items\\arrow_of_long_water_breathing.png",
    "Arrow of Long Weakness" : "Assets\\Items\\arrow_of_long_weakness.png",
    "Arrow of Luck" : "Assets\\Items\\arrow_of_luck.png",
    "Arrow of Night Vision" : "Assets\\Items\\arrow_of_night_vision.png",
    "Arrow of Poison" : "Assets\\Items\\arrow_of_poison.png",
    "Arrow of Regeneration" : "Assets\\Items\\arrow_of_regeneration.png",
    "Arrow of Slowness" : "Assets\\Items\\arrow_of_slowness.png",
    "Arrow of Slow Falling" : "Assets\\Items\\arrow_of_slow_falling.png",
    "Arrow of Strength" : "Assets\\Items\\arrow_of_strength.png",
    "Arrow of Strong Harming" : "Assets\\Items\\arrow_of_strong_harming.png",
    "Arrow of Strong Healing" : "Assets\\Items\\arrow_of_strong_healing.png",
    "Arrow of Strong Leaping" : "Assets\\Items\\arrow_of_strong_leaping.png",
    "Arrow of Strong Poison" : "Assets\\Items\\arrow_of_strong_poison.png",
    "Arrow of Strong Regeneration" : "Assets\\Items\\arrow_of_strong_regeneration.png",
    "Arrow of Strong Slowness" : "Assets\\Items\\arrow_of_strong_slowness.png",
    "Arrow of Strong Strength" : "Assets\\Items\\arrow_of_strong_strength.png",
    "Arrow of Strong Swiftness" : "Assets\\Items\\arrow_of_strong_swiftness.png",
    "Arrow of Strong Turtle Master" : "Assets\\Items\\arrow_of_strong_turtle_master.png",
    "Arrow of Swiftness" : "Assets\\Items\\arrow_of_swiftness.png",
    "Arrow of Turtle Master" : "Assets\\Items\\arrow_of_turtle_master.png",
    "Arrow of Water Breathing" : "Assets\\Items\\arrow_of_water_breathing.png",
    "Arrow of Weakness" : "Assets\\Items\\arrow_of_weakness.png",
    "Azure Bluet" : "Assets\\Items\\azure_bluet.png",
    "Baked Potato" : "Assets\\Items\\baked_potato.png",
    "Bamboo" : "Assets\\Items\\bamboo.png",
    "Barrel" : "Assets\\Items\\barrel.png",
    "Basalt" : "Assets\\Items\\basalt.png",
    "Bat Spawn Egg" : "Assets\\Items\\bat_spawn_egg.png",
    "Beacon" : "Assets\\Items\\beacon.png",
    "Bedrock" : "Assets\\Items\\bedrock.png",
    "Beef" : "Assets\\Items\\beef.png",
    "Beehive" : "Assets\\Items\\beehive.png",
    "Beetroot" : "Assets\\Items\\beetroot.png",
    "Beetroot Seeds" : "Assets\\Items\\beetroot_seeds.png",
    "Beetroot Soup" : "Assets\\Items\\beetroot_soup.png",
    "Bee Nest" : "Assets\\Items\\bee_nest.png",
    "Bee Spawn Egg" : "Assets\\Items\\bee_spawn_egg.png",
    "Bell" : "Assets\\Items\\bell.png",
    "Birch Boat" : "Assets\\Items\\birch_boat.png",
    "Birch Button" : "Assets\\Items\\birch_button.png",
    "Birch Door" : "Assets\\Items\\birch_door.png",
    "Birch Fence" : "Assets\\Items\\birch_fence.png",
    "Birch Fence Gate" : "Assets\\Items\\birch_fence_gate.png",
    "Birch Leaves" : "Assets\\Items\\birch_leaves.png",
    "Birch Log" : "Assets\\Items\\birch_log.png",
    "Birch Planks" : "Assets\\Items\\birch_planks.png",
    "Birch Pressure Plate" : "Assets\\Items\\birch_pressure_plate.png",
    "Birch Sapling" : "Assets\\Items\\birch_sapling.png",
    "Birch Sign" : "Assets\\Items\\birch_sign.png",
    "Birch Slab" : "Assets\\Items\\birch_slab.png",
    "Birch Stairs" : "Assets\\Items\\birch_stairs.png",
    "Birch Trapdoor" : "Assets\\Items\\birch_trapdoor.png",
    "Birch Wood" : "Assets\\Items\\birch_wood.png",
    "Blackstone" : "Assets\\Items\\blackstone.png",
    "Blackstone Slab" : "Assets\\Items\\blackstone_slab.png",
    "Blackstone Stairs" : "Assets\\Items\\blackstone_stairs.png",
    "Blackstone Wall" : "Assets\\Items\\blackstone_wall.png",
    "Black Banner" : "Assets\\Items\\black_banner.png",
    "Black Bed" : "Assets\\Items\\black_bed.png",
    "Black Carpet" : "Assets\\Items\\black_carpet.png",
    "Black Concrete" : "Assets\\Items\\black_concrete.png",
    "Black Concrete Powder" : "Assets\\Items\\black_concrete_powder.png",
    "Black Dye" : "Assets\\Items\\black_dye.png",
    "Black Glazed Terracotta" : "Assets\\Items\\black_glazed_terracotta.png",
    "Black Shulker Box" : "Assets\\Items\\black_shulker_box.png",
    "Black Stained Glass" : "Assets\\Items\\black_stained_glass.png",
    "Black Stained Glass Pane" : "Assets\\Items\\black_stained_glass_pane.png",
    "Black Terracotta" : "Assets\\Items\\black_terracotta.png",
    "Black Wool" : "Assets\\Items\\black_wool.png",
    "Blast Furnace" : "Assets\\Items\\blast_furnace.png",
    "Blaze Powder" : "Assets\\Items\\blaze_powder.png",
    "Blaze Rod" : "Assets\\Items\\blaze_rod.png",
    "Blaze Spawn Egg" : "Assets\\Items\\blaze_spawn_egg.png",
    "Blue Banner" : "Assets\\Items\\blue_banner.png",
    "Blue Bed" : "Assets\\Items\\blue_bed.png",
    "Blue Carpet" : "Assets\\Items\\blue_carpet.png",
    "Blue Concrete" : "Assets\\Items\\blue_concrete.png",
    "Blue Concrete Powder" : "Assets\\Items\\blue_concrete_powder.png",
    "Blue Dye" : "Assets\\Items\\blue_dye.png",
    "Blue Glazed Terracotta" : "Assets\\Items\\blue_glazed_terracotta.png",
    "Blue Ice" : "Assets\\Items\\blue_ice.png",
    "Blue Orchid" : "Assets\\Items\\blue_orchid.png",
    "Blue Shulker Box" : "Assets\\Items\\blue_shulker_box.png",
    "Blue Stained Glass" : "Assets\\Items\\blue_stained_glass.png",
    "Blue Stained Glass Pane" : "Assets\\Items\\blue_stained_glass_pane.png",
    "Blue Terracotta" : "Assets\\Items\\blue_terracotta.png",
    "Blue Wool" : "Assets\\Items\\blue_wool.png",
    "Bone" : "Assets\\Items\\bone.png",
    "Bone Block" : "Assets\\Items\\bone_block.png",
    "Bone Meal" : "Assets\\Items\\bone_meal.png",
    "Book" : "Assets\\Items\\book.png",
    "Bookshelf" : "Assets\\Items\\bookshelf.png",
    "Bow" : "Assets\\Items\\bow.png",
    "Bowl" : "Assets\\Items\\bowl.png",
    "Brain Coral" : "Assets\\Items\\brain_coral.png",
    "Brain Coral Block" : "Assets\\Items\\brain_coral_block.png",
    "Brain Coral Fan" : "Assets\\Items\\brain_coral_fan.png",
    "Bread" : "Assets\\Items\\bread.png",
    "Brewing Stand" : "Assets\\Items\\brewing_stand.png",
    "Brick" : "Assets\\Items\\brick.png",
    "Bricks" : "Assets\\Items\\bricks.png",
    "Brick Slab" : "Assets\\Items\\brick_slab.png",
    "Brick Stairs" : "Assets\\Items\\brick_stairs.png",
    "Brick Wall" : "Assets\\Items\\brick_wall.png",
    "Brown Banner" : "Assets\\Items\\brown_banner.png",
    "Brown Bed" : "Assets\\Items\\brown_bed.png",
    "Brown Carpet" : "Assets\\Items\\brown_carpet.png",
    "Brown Concrete" : "Assets\\Items\\brown_concrete.png",
    "Brown Concrete Powder" : "Assets\\Items\\brown_concrete_powder.png",
    "Brown Dye" : "Assets\\Items\\brown_dye.png",
    "Brown Glazed Terracotta" : "Assets\\Items\\brown_glazed_terracotta.png",
    "Brown Mushroom" : "Assets\\Items\\brown_mushroom.png",
    "Brown Mushroom Block" : "Assets\\Items\\brown_mushroom_block.png",
    "Brown Shulker Box" : "Assets\\Items\\brown_shulker_box.png",
    "Brown Stained Glass" : "Assets\\Items\\brown_stained_glass.png",
    "Brown Stained Glass Pane" : "Assets\\Items\\brown_stained_glass_pane.png",
    "Brown Terracotta" : "Assets\\Items\\brown_terracotta.png",
    "Brown Wool" : "Assets\\Items\\brown_wool.png",
    "Bubble Coral" : "Assets\\Items\\bubble_coral.png",
    "Bubble Coral Block" : "Assets\\Items\\bubble_coral_block.png",
    "Bubble Coral Fan" : "Assets\\Items\\bubble_coral_fan.png",
    "Bucket" : "Assets\\Items\\bucket.png",
    "Cactus" : "Assets\\Items\\cactus.png",
    "Cake" : "Assets\\Items\\cake.png",
    "Campfire" : "Assets\\Items\\campfire.png",
    "Carrot" : "Assets\\Items\\carrot.png",
    "Carrot On A Stick" : "Assets\\Items\\carrot_on_a_stick.png",
    "Cartography Table" : "Assets\\Items\\cartography_table.png",
    "Carved Pumpkin" : "Assets\\Items\\carved_pumpkin.png",
    "Cat Spawn Egg" : "Assets\\Items\\cat_spawn_egg.png",
    "Cauldron" : "Assets\\Items\\cauldron.png",
    "Cave Spider Spawn Egg" : "Assets\\Items\\cave_spider_spawn_egg.png",
    "Chain" : "Assets\\Items\\chain.png",
    "Chainmail Boots" : "Assets\\Items\\chainmail_boots.png",
    "Chainmail Chestplate" : "Assets\\Items\\chainmail_chestplate.png",
    "Chainmail Helmet" : "Assets\\Items\\chainmail_helmet.png",
    "Chainmail Leggings" : "Assets\\Items\\chainmail_leggings.png",
    "Charcoal" : "Assets\\Items\\charcoal.png",
    "Chest" : "Assets\\Items\\chest.png",
    "Chest Minecart" : "Assets\\Items\\chest_minecart.png",
    "Chicken" : "Assets\\Items\\chicken.png",
    "Chicken Spawn Egg" : "Assets\\Items\\chicken_spawn_egg.png",
    "Chipped Anvil" : "Assets\\Items\\chipped_anvil.png",
    "Chiseled Nether Bricks" : "Assets\\Items\\chiseled_nether_bricks.png",
    "Chiseled Polished Blackstone" : "Assets\\Items\\chiseled_polished_blackstone.png",
    "Chiseled Quartz Block" : "Assets\\Items\\chiseled_quartz_block.png",
    "Chiseled Red Sandstone" : "Assets\\Items\\chiseled_red_sandstone.png",
    "Chiseled Sandstone" : "Assets\\Items\\chiseled_sandstone.png",
    "Chiseled Stone Bricks" : "Assets\\Items\\chiseled_stone_bricks.png",
    "Chorus Flower" : "Assets\\Items\\chorus_flower.png",
    "Chorus Fruit" : "Assets\\Items\\chorus_fruit.png",
    "Chorus Plant" : "Assets\\Items\\chorus_plant.png",
    "Clay" : "Assets\\Items\\clay.png",
    "Clay Ball" : "Assets\\Items\\clay_ball.png",
    "Clock" : "Assets\\Items\\clock.png",
    "Coal" : "Assets\\Items\\coal.png",
    "Coal Block" : "Assets\\Items\\coal_block.png",
    "Coal Ore" : "Assets\\Items\\coal_ore.png",
    "Coarse Dirt" : "Assets\\Items\\coarse_dirt.png",
    "Cobblestone" : "Assets\\Items\\cobblestone.png",
    "Cobblestone Slab" : "Assets\\Items\\cobblestone_slab.png",
    "Cobblestone Stairs" : "Assets\\Items\\cobblestone_stairs.png",
    "Cobblestone Wall" : "Assets\\Items\\cobblestone_wall.png",
    "Cobweb" : "Assets\\Items\\cobweb.png",
    "Cocoa Beans" : "Assets\\Items\\cocoa_beans.png",
    "Cod" : "Assets\\Items\\cod.png",
    "Cod Bucket" : "Assets\\Items\\cod_bucket.png",
    "Cod Spawn Egg" : "Assets\\Items\\cod_spawn_egg.png",
    "Comparator" : "Assets\\Items\\comparator.png",
    "Compass" : "Assets\\Items\\compass.png",
    "Composter" : "Assets\\Items\\composter.png",
    "Conduit" : "Assets\\Items\\conduit.png",
    "Cooked Beef" : "Assets\\Items\\cooked_beef.png",
    "Cooked Chicken" : "Assets\\Items\\cooked_chicken.png",
    "Cooked Cod" : "Assets\\Items\\cooked_cod.png",
    "Cooked Mutton" : "Assets\\Items\\cooked_mutton.png",
    "Cooked Porkchop" : "Assets\\Items\\cooked_porkchop.png",
    "Cooked Rabbit" : "Assets\\Items\\cooked_rabbit.png",
    "Cooked Salmon" : "Assets\\Items\\cooked_salmon.png",
    "Cookie" : "Assets\\Items\\cookie.png",
    "Cornflower" : "Assets\\Items\\cornflower.png",
    "Cow Spawn Egg" : "Assets\\Items\\cow_spawn_egg.png",
    "Cracked Nether Bricks" : "Assets\\Items\\cracked_nether_bricks.png",
    "Cracked Polished Blackstone Bricks" : "Assets\\Items\\cracked_polished_blackstone_bricks.png",
    "Cracked Stone Bricks" : "Assets\\Items\\cracked_stone_bricks.png",
    "Crafting Table" : "Assets\\Items\\crafting_table.png",
    "Creeper Banner Pattern" : "Assets\\Items\\creeper_banner_pattern.png",
    "Creeper Head" : "Assets\\Items\\creeper_head.png",
    "Creeper Spawn Egg" : "Assets\\Items\\creeper_spawn_egg.png",
    "Crimson Button" : "Assets\\Items\\crimson_button.png",
    "Crimson Door" : "Assets\\Items\\crimson_door.png",
    "Crimson Fence" : "Assets\\Items\\crimson_fence.png",
    "Crimson Fence Gate" : "Assets\\Items\\crimson_fence_gate.png",
    "Crimson Fungus" : "Assets\\Items\\crimson_fungus.png",
    "Crimson Hyphae" : "Assets\\Items\\crimson_hyphae.png",
    "Crimson Nylium" : "Assets\\Items\\crimson_nylium.png",
    "Crimson Planks" : "Assets\\Items\\crimson_planks.png",
    "Crimson Pressure Plate" : "Assets\\Items\\crimson_pressure_plate.png",
    "Crimson Roots" : "Assets\\Items\\crimson_roots.png",
    "Crimson Sign" : "Assets\\Items\\crimson_sign.png",
    "Crimson Slab" : "Assets\\Items\\crimson_slab.png",
    "Crimson Stairs" : "Assets\\Items\\crimson_stairs.png",
    "Crimson Stem" : "Assets\\Items\\crimson_stem.png",
    "Crimson Trapdoor" : "Assets\\Items\\crimson_trapdoor.png",
    "Crossbow" : "Assets\\Items\\crossbow.png",
    "Crying Obsidian" : "Assets\\Items\\crying_obsidian.png",
    "Cut Red Sandstone" : "Assets\\Items\\cut_red_sandstone.png",
    "Cut Red Sandstone Slab" : "Assets\\Items\\cut_red_sandstone_slab.png",
    "Cut Sandstone" : "Assets\\Items\\cut_sandstone.png",
    "Cut Sandstone Slab" : "Assets\\Items\\cut_sandstone_slab.png",
    "Cyan Banner" : "Assets\\Items\\cyan_banner.png",
    "Cyan Bed" : "Assets\\Items\\cyan_bed.png",
    "Cyan Carpet" : "Assets\\Items\\cyan_carpet.png",
    "Cyan Concrete" : "Assets\\Items\\cyan_concrete.png",
    "Cyan Concrete Powder" : "Assets\\Items\\cyan_concrete_powder.png",
    "Cyan Dye" : "Assets\\Items\\cyan_dye.png",
    "Cyan Glazed Terracotta" : "Assets\\Items\\cyan_glazed_terracotta.png",
    "Cyan Shulker Box" : "Assets\\Items\\cyan_shulker_box.png",
    "Cyan Stained Glass" : "Assets\\Items\\cyan_stained_glass.png",
    "Cyan Stained Glass Pane" : "Assets\\Items\\cyan_stained_glass_pane.png",
    "Cyan Terracotta" : "Assets\\Items\\cyan_terracotta.png",
    "Cyan Wool" : "Assets\\Items\\cyan_wool.png",
    "Damaged Anvil" : "Assets\\Items\\damaged_anvil.png",
    "Dandelion" : "Assets\\Items\\dandelion.png",
    "Dark Oak Boat" : "Assets\\Items\\dark_oak_boat.png",
    "Dark Oak Button" : "Assets\\Items\\dark_oak_button.png",
    "Dark Oak Door" : "Assets\\Items\\dark_oak_door.png",
    "Dark Oak Fence" : "Assets\\Items\\dark_oak_fence.png",
    "Dark Oak Fence Gate" : "Assets\\Items\\dark_oak_fence_gate.png",
    "Dark Oak Leaves" : "Assets\\Items\\dark_oak_leaves.png",
    "Dark Oak Log" : "Assets\\Items\\dark_oak_log.png",
    "Dark Oak Planks" : "Assets\\Items\\dark_oak_planks.png",
    "Dark Oak Pressure Plate" : "Assets\\Items\\dark_oak_pressure_plate.png",
    "Dark Oak Sapling" : "Assets\\Items\\dark_oak_sapling.png",
    "Dark Oak Sign" : "Assets\\Items\\dark_oak_sign.png",
    "Dark Oak Slab" : "Assets\\Items\\dark_oak_slab.png",
    "Dark Oak Stairs" : "Assets\\Items\\dark_oak_stairs.png",
    "Dark Oak Trapdoor" : "Assets\\Items\\dark_oak_trapdoor.png",
    "Dark Oak Wood" : "Assets\\Items\\dark_oak_wood.png",
    "Dark Prismarine" : "Assets\\Items\\dark_prismarine.png",
    "Dark Prismarine Slab" : "Assets\\Items\\dark_prismarine_slab.png",
    "Dark Prismarine Stairs" : "Assets\\Items\\dark_prismarine_stairs.png",
    "Daylight Detector" : "Assets\\Items\\daylight_detector.png",
    "Dead Brain Coral" : "Assets\\Items\\dead_brain_coral.png",
    "Dead Brain Coral Block" : "Assets\\Items\\dead_brain_coral_block.png",
    "Dead Brain Coral Fan" : "Assets\\Items\\dead_brain_coral_fan.png",
    "Dead Bubble Coral" : "Assets\\Items\\dead_bubble_coral.png",
    "Dead Bubble Coral Block" : "Assets\\Items\\dead_bubble_coral_block.png",
    "Dead Bubble Coral Fan" : "Assets\\Items\\dead_bubble_coral_fan.png",
    "Dead Bush" : "Assets\\Items\\dead_bush.png",
    "Dead Fire Coral" : "Assets\\Items\\dead_fire_coral.png",
    "Dead Fire Coral Block" : "Assets\\Items\\dead_fire_coral_block.png",
    "Dead Fire Coral Fan" : "Assets\\Items\\dead_fire_coral_fan.png",
    "Dead Horn Coral" : "Assets\\Items\\dead_horn_coral.png",
    "Dead Horn Coral Block" : "Assets\\Items\\dead_horn_coral_block.png",
    "Dead Horn Coral Fan" : "Assets\\Items\\dead_horn_coral_fan.png",
    "Dead Tube Coral" : "Assets\\Items\\dead_tube_coral.png",
    "Dead Tube Coral Block" : "Assets\\Items\\dead_tube_coral_block.png",
    "Dead Tube Coral Fan" : "Assets\\Items\\dead_tube_coral_fan.png",
    "Detector Rail" : "Assets\\Items\\detector_rail.png",
    "Diamond" : "Assets\\Items\\diamond.png",
    "Diamond Axe" : "Assets\\Items\\diamond_axe.png",
    "Diamond Block" : "Assets\\Items\\diamond_block.png",
    "Diamond Boots" : "Assets\\Items\\diamond_boots.png",
    "Diamond Chestplate" : "Assets\\Items\\diamond_chestplate.png",
    "Diamond Helmet" : "Assets\\Items\\diamond_helmet.png",
    "Diamond Hoe" : "Assets\\Items\\diamond_hoe.png",
    "Diamond Horse Armor" : "Assets\\Items\\diamond_horse_armor.png",
    "Diamond Leggings" : "Assets\\Items\\diamond_leggings.png",
    "Diamond Ore" : "Assets\\Items\\diamond_ore.png",
    "Diamond Pickaxe" : "Assets\\Items\\diamond_pickaxe.png",
    "Diamond Shovel" : "Assets\\Items\\diamond_shovel.png",
    "Diamond Sword" : "Assets\\Items\\diamond_sword.png",
    "Diorite" : "Assets\\Items\\diorite.png",
    "Diorite Slab" : "Assets\\Items\\diorite_slab.png",
    "Diorite Stairs" : "Assets\\Items\\diorite_stairs.png",
    "Diorite Wall" : "Assets\\Items\\diorite_wall.png",
    "Dirt" : "Assets\\Items\\dirt.png",
    "Dispenser" : "Assets\\Items\\dispenser.png",
    "Dolphin Spawn Egg" : "Assets\\Items\\dolphin_spawn_egg.png",
    "Donkey Spawn Egg" : "Assets\\Items\\donkey_spawn_egg.png",
    "Dragon Breath" : "Assets\\Items\\dragon_breath.png",
    "Dragon Head" : "Assets\\Items\\dragon_head.png",
    "Dried Kelp" : "Assets\\Items\\dried_kelp.png",
    "Dried Kelp Block" : "Assets\\Items\\dried_kelp_block.png",
    "Dropper" : "Assets\\Items\\dropper.png",
    "Drowned Spawn Egg" : "Assets\\Items\\drowned_spawn_egg.png",
    "Egg" : "Assets\\Items\\egg.png",
    "Elder Guardian Spawn Egg" : "Assets\\Items\\elder_guardian_spawn_egg.png",
    "Elytra" : "Assets\\Items\\elytra.png",
    "Emerald" : "Assets\\Items\\emerald.png",
    "Emerald Block" : "Assets\\Items\\emerald_block.png",
    "Emerald Ore" : "Assets\\Items\\emerald_ore.png",
    "Enchanted Book" : "Assets\\Items\\enchanted_book.png",
    "Enchanted Golden Apple" : "Assets\\Items\\enchanted_golden_apple.png",
    "Enchanting Table" : "Assets\\Items\\enchanting_table.png",
    "Enderman Spawn Egg" : "Assets\\Items\\enderman_spawn_egg.png",
    "Endermite Spawn Egg" : "Assets\\Items\\endermite_spawn_egg.png",
    "Ender Chest" : "Assets\\Items\\ender_chest.png",
    "Ender Eye" : "Assets\\Items\\ender_eye.png",
    "Ender Pearl" : "Assets\\Items\\ender_pearl.png",
    "End Crystal" : "Assets\\Items\\end_crystal.png",
    "End Portal Frame" : "Assets\\Items\\end_portal_frame.png",
    "End Rod" : "Assets\\Items\\end_rod.png",
    "End Stone" : "Assets\\Items\\end_stone.png",
    "End Stone Bricks" : "Assets\\Items\\end_stone_bricks.png",
    "End Stone Brick Slab" : "Assets\\Items\\end_stone_brick_slab.png",
    "End Stone Brick Stairs" : "Assets\\Items\\end_stone_brick_stairs.png",
    "End Stone Brick Wall" : "Assets\\Items\\end_stone_brick_wall.png",
    "Evoker Spawn Egg" : "Assets\\Items\\evoker_spawn_egg.png",
    "Experience Bottle" : "Assets\\Items\\experience_bottle.png",
    "Farmland" : "Assets\\Items\\farmland.png",
    "Feather" : "Assets\\Items\\feather.png",
    "Fermented Spider Eye" : "Assets\\Items\\fermented_spider_eye.png",
    "Fern" : "Assets\\Items\\fern.png",
    "Firework Rocket" : "Assets\\Items\\firework_rocket.png",
    "Firework Star" : "Assets\\Items\\firework_star.png",
    "Fire Charge" : "Assets\\Items\\fire_charge.png",
    "Fire Coral" : "Assets\\Items\\fire_coral.png",
    "Fire Coral Block" : "Assets\\Items\\fire_coral_block.png",
    "Fire Coral Fan" : "Assets\\Items\\fire_coral_fan.png",
    "Fishing Rod" : "Assets\\Items\\fishing_rod.png",
    "Fletching Table" : "Assets\\Items\\fletching_table.png",
    "Flint" : "Assets\\Items\\flint.png",
    "Flint And Steel" : "Assets\\Items\\flint_and_steel.png",
    "Flower Banner Pattern" : "Assets\\Items\\flower_banner_pattern.png",
    "Flower Pot" : "Assets\\Items\\flower_pot.png",
    "Fox Spawn Egg" : "Assets\\Items\\fox_spawn_egg.png",
    "Furnace" : "Assets\\Items\\furnace.png",
    "Furnace Minecart" : "Assets\\Items\\furnace_minecart.png",
    "Ghast Spawn Egg" : "Assets\\Items\\ghast_spawn_egg.png",
    "Ghast Tear" : "Assets\\Items\\ghast_tear.png",
    "Gilded Blackstone" : "Assets\\Items\\gilded_blackstone.png",
    "Glass" : "Assets\\Items\\glass.png",
    "Glass Bottle" : "Assets\\Items\\glass_bottle.png",
    "Glass Pane" : "Assets\\Items\\glass_pane.png",
    "Glistering Melon Slice" : "Assets\\Items\\glistering_melon_slice.png",
    "Globe Banner Pattern" : "Assets\\Items\\globe_banner_pattern.png",
    "Glowstone" : "Assets\\Items\\glowstone.png",
    "Glowstone Dust" : "Assets\\Items\\glowstone_dust.png",
    "Golden Apple" : "Assets\\Items\\golden_apple.png",
    "Golden Axe" : "Assets\\Items\\golden_axe.png",
    "Golden Boots" : "Assets\\Items\\golden_boots.png",
    "Golden Carrot" : "Assets\\Items\\golden_carrot.png",
    "Golden Chestplate" : "Assets\\Items\\golden_chestplate.png",
    "Golden Helmet" : "Assets\\Items\\golden_helmet.png",
    "Golden Hoe" : "Assets\\Items\\golden_hoe.png",
    "Golden Horse Armor" : "Assets\\Items\\golden_horse_armor.png",
    "Golden Leggings" : "Assets\\Items\\golden_leggings.png",
    "Golden Pickaxe" : "Assets\\Items\\golden_pickaxe.png",
    "Golden Shovel" : "Assets\\Items\\golden_shovel.png",
    "Golden Sword" : "Assets\\Items\\golden_sword.png",
    "Gold Block" : "Assets\\Items\\gold_block.png",
    "Gold Ingot" : "Assets\\Items\\gold_ingot.png",
    "Gold Nugget" : "Assets\\Items\\gold_nugget.png",
    "Gold Ore" : "Assets\\Items\\gold_ore.png",
    "Granite" : "Assets\\Items\\granite.png",
    "Granite Slab" : "Assets\\Items\\granite_slab.png",
    "Granite Stairs" : "Assets\\Items\\granite_stairs.png",
    "Granite Wall" : "Assets\\Items\\granite_wall.png",
    "Grass" : "Assets\\Items\\grass.png",
    "Grass Block" : "Assets\\Items\\grass_block.png",
    "Grass Path" : "Assets\\Items\\grass_path.png",
    "Gravel" : "Assets\\Items\\gravel.png",
    "Gray Banner" : "Assets\\Items\\gray_banner.png",
    "Gray Bed" : "Assets\\Items\\gray_bed.png",
    "Gray Carpet" : "Assets\\Items\\gray_carpet.png",
    "Gray Concrete" : "Assets\\Items\\gray_concrete.png",
    "Gray Concrete Powder" : "Assets\\Items\\gray_concrete_powder.png",
    "Gray Dye" : "Assets\\Items\\gray_dye.png",
    "Gray Glazed Terracotta" : "Assets\\Items\\gray_glazed_terracotta.png",
    "Gray Shulker Box" : "Assets\\Items\\gray_shulker_box.png",
    "Gray Stained Glass" : "Assets\\Items\\gray_stained_glass.png",
    "Gray Stained Glass Pane" : "Assets\\Items\\gray_stained_glass_pane.png",
    "Gray Terracotta" : "Assets\\Items\\gray_terracotta.png",
    "Gray Wool" : "Assets\\Items\\gray_wool.png",
    "Green Banner" : "Assets\\Items\\green_banner.png",
    "Green Bed" : "Assets\\Items\\green_bed.png",
    "Green Carpet" : "Assets\\Items\\green_carpet.png",
    "Green Concrete" : "Assets\\Items\\green_concrete.png",
    "Green Concrete Powder" : "Assets\\Items\\green_concrete_powder.png",
    "Green Dye" : "Assets\\Items\\green_dye.png",
    "Green Glazed Terracotta" : "Assets\\Items\\green_glazed_terracotta.png",
    "Green Shulker Box" : "Assets\\Items\\green_shulker_box.png",
    "Green Stained Glass" : "Assets\\Items\\green_stained_glass.png",
    "Green Stained Glass Pane" : "Assets\\Items\\green_stained_glass_pane.png",
    "Green Terracotta" : "Assets\\Items\\green_terracotta.png",
    "Green Wool" : "Assets\\Items\\green_wool.png",
    "Grindstone" : "Assets\\Items\\grindstone.png",
    "Guardian Spawn Egg" : "Assets\\Items\\guardian_spawn_egg.png",
    "Gunpowder" : "Assets\\Items\\gunpowder.png",
    "Hay Block" : "Assets\\Items\\hay_block.png",
    "Heart of The Sea" : "Assets\\Items\\heart_of_the_sea.png",
    "Heavy Weighted Pressure Plate" : "Assets\\Items\\heavy_weighted_pressure_plate.png",
    "Hoglin Spawn Egg" : "Assets\\Items\\hoglin_spawn_egg.png",
    "Honeycomb" : "Assets\\Items\\honeycomb.png",
    "Honeycomb Block" : "Assets\\Items\\honeycomb_block.png",
    "Honey Block" : "Assets\\Items\\honey_block.png",
    "Honey Bottle" : "Assets\\Items\\honey_bottle.png",
    "Hopper" : "Assets\\Items\\hopper.png",
    "Hopper Minecart" : "Assets\\Items\\hopper_minecart.png",
    "Horn Coral" : "Assets\\Items\\horn_coral.png",
    "Horn Coral Block" : "Assets\\Items\\horn_coral_block.png",
    "Horn Coral Fan" : "Assets\\Items\\horn_coral_fan.png",
    "Horse Spawn Egg" : "Assets\\Items\\horse_spawn_egg.png",
    "Husk Spawn Egg" : "Assets\\Items\\husk_spawn_egg.png",
    "Ice" : "Assets\\Items\\ice.png",
    "Infested Chiseled Stone Bricks" : "Assets\\Items\\infested_chiseled_stone_bricks.png",
    "Infested Cobblestone" : "Assets\\Items\\infested_cobblestone.png",
    "Infested Cracked Stone Bricks" : "Assets\\Items\\infested_cracked_stone_bricks.png",
    "Infested Mossy Stone Bricks" : "Assets\\Items\\infested_mossy_stone_bricks.png",
    "Infested Stone" : "Assets\\Items\\infested_stone.png",
    "Infested Stone Bricks" : "Assets\\Items\\infested_stone_bricks.png",
    "Ink Sac" : "Assets\\Items\\ink_sac.png",
    "Iron Axe" : "Assets\\Items\\iron_axe.png",
    "Iron Bars" : "Assets\\Items\\iron_bars.png",
    "Iron Block" : "Assets\\Items\\iron_block.png",
    "Iron Boots" : "Assets\\Items\\iron_boots.png",
    "Iron Chestplate" : "Assets\\Items\\iron_chestplate.png",
    "Iron Door" : "Assets\\Items\\iron_door.png",
    "Iron Helmet" : "Assets\\Items\\iron_helmet.png",
    "Iron Hoe" : "Assets\\Items\\iron_hoe.png",
    "Iron Horse Armor" : "Assets\\Items\\iron_horse_armor.png",
    "Iron Ingot" : "Assets\\Items\\iron_ingot.png",
    "Iron Leggings" : "Assets\\Items\\iron_leggings.png",
    "Iron Nugget" : "Assets\\Items\\iron_nugget.png",
    "Iron Ore" : "Assets\\Items\\iron_ore.png",
    "Iron Pickaxe" : "Assets\\Items\\iron_pickaxe.png",
    "Iron Shovel" : "Assets\\Items\\iron_shovel.png",
    "Iron Sword" : "Assets\\Items\\iron_sword.png",
    "Iron Trapdoor" : "Assets\\Items\\iron_trapdoor.png",
    "Item Frame" : "Assets\\Items\\item_frame.png",
    "Jack O Lantern" : "Assets\\Items\\jack_o_lantern.png",
    "Jukebox" : "Assets\\Items\\jukebox.png",
    "Jungle Boat" : "Assets\\Items\\jungle_boat.png",
    "Jungle Button" : "Assets\\Items\\jungle_button.png",
    "Jungle Door" : "Assets\\Items\\jungle_door.png",
    "Jungle Fence" : "Assets\\Items\\jungle_fence.png",
    "Jungle Fence Gate" : "Assets\\Items\\jungle_fence_gate.png",
    "Jungle Leaves" : "Assets\\Items\\jungle_leaves.png",
    "Jungle Log" : "Assets\\Items\\jungle_log.png",
    "Jungle Planks" : "Assets\\Items\\jungle_planks.png",
    "Jungle Pressure Plate" : "Assets\\Items\\jungle_pressure_plate.png",
    "Jungle Sapling" : "Assets\\Items\\jungle_sapling.png",
    "Jungle Sign" : "Assets\\Items\\jungle_sign.png",
    "Jungle Slab" : "Assets\\Items\\jungle_slab.png",
    "Jungle Stairs" : "Assets\\Items\\jungle_stairs.png",
    "Jungle Trapdoor" : "Assets\\Items\\jungle_trapdoor.png",
    "Jungle Wood" : "Assets\\Items\\jungle_wood.png",
    "Kelp" : "Assets\\Items\\kelp.png",
    "Ladder" : "Assets\\Items\\ladder.png",
    "Lantern" : "Assets\\Items\\lantern.png",
    "Lapis Block" : "Assets\\Items\\lapis_block.png",
    "Lapis Lazuli" : "Assets\\Items\\lapis_lazuli.png",
    "Lapis Ore" : "Assets\\Items\\lapis_ore.png",
    "Large Fern" : "Assets\\Items\\large_fern.png",
    "Lava Bucket" : "Assets\\Items\\lava_bucket.png",
    "Lead" : "Assets\\Items\\lead.png",
    "Leather" : "Assets\\Items\\leather.png",
    "Leather Boots" : "Assets\\Items\\leather_boots.png",
    "Leather Chestplate" : "Assets\\Items\\leather_chestplate.png",
    "Leather Helmet" : "Assets\\Items\\leather_helmet.png",
    "Leather Horse Armor" : "Assets\\Items\\leather_horse_armor.png",
    "Leather Leggings" : "Assets\\Items\\leather_leggings.png",
    "Lectern" : "Assets\\Items\\lectern.png",
    "Lever" : "Assets\\Items\\lever.png",
    "Light Blue Banner" : "Assets\\Items\\light_blue_banner.png",
    "Light Blue Bed" : "Assets\\Items\\light_blue_bed.png",
    "Light Blue Carpet" : "Assets\\Items\\light_blue_carpet.png",
    "Light Blue Concrete" : "Assets\\Items\\light_blue_concrete.png",
    "Light Blue Concrete Powder" : "Assets\\Items\\light_blue_concrete_powder.png",
    "Light Blue Dye" : "Assets\\Items\\light_blue_dye.png",
    "Light Blue Glazed Terracotta" : "Assets\\Items\\light_blue_glazed_terracotta.png",
    "Light Blue Shulker Box" : "Assets\\Items\\light_blue_shulker_box.png",
    "Light Blue Stained Glass" : "Assets\\Items\\light_blue_stained_glass.png",
    "Light Blue Stained Glass Pane" : "Assets\\Items\\light_blue_stained_glass_pane.png",
    "Light Blue Terracotta" : "Assets\\Items\\light_blue_terracotta.png",
    "Light Blue Wool" : "Assets\\Items\\light_blue_wool.png",
    "Light Gray Banner" : "Assets\\Items\\light_gray_banner.png",
    "Light Gray Bed" : "Assets\\Items\\light_gray_bed.png",
    "Light Gray Carpet" : "Assets\\Items\\light_gray_carpet.png",
    "Light Gray Concrete" : "Assets\\Items\\light_gray_concrete.png",
    "Light Gray Concrete Powder" : "Assets\\Items\\light_gray_concrete_powder.png",
    "Light Gray Dye" : "Assets\\Items\\light_gray_dye.png",
    "Light Gray Glazed Terracotta" : "Assets\\Items\\light_gray_glazed_terracotta.png",
    "Light Gray Shulker Box" : "Assets\\Items\\light_gray_shulker_box.png",
    "Light Gray Stained Glass" : "Assets\\Items\\light_gray_stained_glass.png",
    "Light Gray Stained Glass Pane" : "Assets\\Items\\light_gray_stained_glass_pane.png",
    "Light Gray Terracotta" : "Assets\\Items\\light_gray_terracotta.png",
    "Light Gray Wool" : "Assets\\Items\\light_gray_wool.png",
    "Light Weighted Pressure Plate" : "Assets\\Items\\light_weighted_pressure_plate.png",
    "Lilac" : "Assets\\Items\\lilac.png",
    "Lily of The Valley" : "Assets\\Items\\lily_of_the_valley.png",
    "Lily Pad" : "Assets\\Items\\lily_pad.png",
    "Lime Banner" : "Assets\\Items\\lime_banner.png",
    "Lime Bed" : "Assets\\Items\\lime_bed.png",
    "Lime Carpet" : "Assets\\Items\\lime_carpet.png",
    "Lime Concrete" : "Assets\\Items\\lime_concrete.png",
    "Lime Concrete Powder" : "Assets\\Items\\lime_concrete_powder.png",
    "Lime Dye" : "Assets\\Items\\lime_dye.png",
    "Lime Glazed Terracotta" : "Assets\\Items\\lime_glazed_terracotta.png",
    "Lime Shulker Box" : "Assets\\Items\\lime_shulker_box.png",
    "Lime Stained Glass" : "Assets\\Items\\lime_stained_glass.png",
    "Lime Stained Glass Pane" : "Assets\\Items\\lime_stained_glass_pane.png",
    "Lime Terracotta" : "Assets\\Items\\lime_terracotta.png",
    "Lime Wool" : "Assets\\Items\\lime_wool.png",
    "Lingering Potion of Awkward" : "Assets\\Items\\lingering_potion_of_awkward.png",
    "Lingering Potion of Fire Resistance" : "Assets\\Items\\lingering_potion_of_fire_resistance.png",
    "Lingering Potion of Harming" : "Assets\\Items\\lingering_potion_of_harming.png",
    "Lingering Potion of Healing" : "Assets\\Items\\lingering_potion_of_healing.png",
    "Lingering Potion of Invisibility" : "Assets\\Items\\lingering_potion_of_invisibility.png",
    "Lingering Potion of Leaping" : "Assets\\Items\\lingering_potion_of_leaping.png",
    "Lingering Potion of Long Fire Resistance" : "Assets\\Items\\lingering_potion_of_long_fire_resistance.png",
    "Lingering Potion of Long Invisibility" : "Assets\\Items\\lingering_potion_of_long_invisibility.png",
    "Lingering Potion of Long Leaping" : "Assets\\Items\\lingering_potion_of_long_leaping.png",
    "Lingering Potion of Long Night Vision" : "Assets\\Items\\lingering_potion_of_long_night_vision.png",
    "Lingering Potion of Long Poison" : "Assets\\Items\\lingering_potion_of_long_poison.png",
    "Lingering Potion of Long Regeneration" : "Assets\\Items\\lingering_potion_of_long_regeneration.png",
    "Lingering Potion of Long Slowness" : "Assets\\Items\\lingering_potion_of_long_slowness.png",
    "Lingering Potion of Long Slow Falling" : "Assets\\Items\\lingering_potion_of_long_slow_falling.png",
    "Lingering Potion of Long Strength" : "Assets\\Items\\lingering_potion_of_long_strength.png",
    "Lingering Potion of Long Swiftness" : "Assets\\Items\\lingering_potion_of_long_swiftness.png",
    "Lingering Potion of Long Turtle Master" : "Assets\\Items\\lingering_potion_of_long_turtle_master.png",
    "Lingering Potion of Long Water Breathing" : "Assets\\Items\\lingering_potion_of_long_water_breathing.png",
    "Lingering Potion of Long Weakness" : "Assets\\Items\\lingering_potion_of_long_weakness.png",
    "Lingering Potion of Luck" : "Assets\\Items\\lingering_potion_of_luck.png",
    "Lingering Potion of Mundane" : "Assets\\Items\\lingering_potion_of_mundane.png",
    "Lingering Potion of Night Vision" : "Assets\\Items\\lingering_potion_of_night_vision.png",
    "Lingering Potion of Poison" : "Assets\\Items\\lingering_potion_of_poison.png",
    "Lingering Potion of Regeneration" : "Assets\\Items\\lingering_potion_of_regeneration.png",
    "Lingering Potion of Slowness" : "Assets\\Items\\lingering_potion_of_slowness.png",
    "Lingering Potion of Slow Falling" : "Assets\\Items\\lingering_potion_of_slow_falling.png",
    "Lingering Potion of Strength" : "Assets\\Items\\lingering_potion_of_strength.png",
    "Lingering Potion of Strong Harming" : "Assets\\Items\\lingering_potion_of_strong_harming.png",
    "Lingering Potion of Strong Healing" : "Assets\\Items\\lingering_potion_of_strong_healing.png",
    "Lingering Potion of Strong Leaping" : "Assets\\Items\\lingering_potion_of_strong_leaping.png",
    "Lingering Potion of Strong Poison" : "Assets\\Items\\lingering_potion_of_strong_poison.png",
    "Lingering Potion of Strong Regeneration" : "Assets\\Items\\lingering_potion_of_strong_regeneration.png",
    "Lingering Potion of Strong Slowness" : "Assets\\Items\\lingering_potion_of_strong_slowness.png",
    "Lingering Potion of Strong Strength" : "Assets\\Items\\lingering_potion_of_strong_strength.png",
    "Lingering Potion of Strong Swiftness" : "Assets\\Items\\lingering_potion_of_strong_swiftness.png",
    "Lingering Potion of Strong Turtle Master" : "Assets\\Items\\lingering_potion_of_strong_turtle_master.png",
    "Lingering Potion of Swiftness" : "Assets\\Items\\lingering_potion_of_swiftness.png",
    "Lingering Potion of Thick" : "Assets\\Items\\lingering_potion_of_thick.png",
    "Lingering Potion of Turtle Master" : "Assets\\Items\\lingering_potion_of_turtle_master.png",
    "Lingering Potion of Water" : "Assets\\Items\\lingering_potion_of_water.png",
    "Lingering Potion of Water Breathing" : "Assets\\Items\\lingering_potion_of_water_breathing.png",
    "Lingering Potion of Weakness" : "Assets\\Items\\lingering_potion_of_weakness.png",
    "Llama Spawn Egg" : "Assets\\Items\\llama_spawn_egg.png",
    "Lodestone" : "Assets\\Items\\lodestone.png",
    "Loom" : "Assets\\Items\\loom.png",
    "Magenta Banner" : "Assets\\Items\\magenta_banner.png",
    "Magenta Bed" : "Assets\\Items\\magenta_bed.png",
    "Magenta Carpet" : "Assets\\Items\\magenta_carpet.png",
    "Magenta Concrete" : "Assets\\Items\\magenta_concrete.png",
    "Magenta Concrete Powder" : "Assets\\Items\\magenta_concrete_powder.png",
    "Magenta Dye" : "Assets\\Items\\magenta_dye.png",
    "Magenta Glazed Terracotta" : "Assets\\Items\\magenta_glazed_terracotta.png",
    "Magenta Shulker Box" : "Assets\\Items\\magenta_shulker_box.png",
    "Magenta Stained Glass" : "Assets\\Items\\magenta_stained_glass.png",
    "Magenta Stained Glass Pane" : "Assets\\Items\\magenta_stained_glass_pane.png",
    "Magenta Terracotta" : "Assets\\Items\\magenta_terracotta.png",
    "Magenta Wool" : "Assets\\Items\\magenta_wool.png",
    "Magma Block" : "Assets\\Items\\magma_block.png",
    "Magma Cream" : "Assets\\Items\\magma_cream.png",
    "Magma Cube Spawn Egg" : "Assets\\Items\\magma_cube_spawn_egg.png",
    "Map" : "Assets\\Items\\map.png",
    "Melon" : "Assets\\Items\\melon.png",
    "Melon Seeds" : "Assets\\Items\\melon_seeds.png",
    "Melon Slice" : "Assets\\Items\\melon_slice.png",
    "Milk Bucket" : "Assets\\Items\\milk_bucket.png",
    "Minecart" : "Assets\\Items\\minecart.png",
    "Mojang Banner Pattern" : "Assets\\Items\\mojang_banner_pattern.png",
    "Mooshroom Spawn Egg" : "Assets\\Items\\mooshroom_spawn_egg.png",
    "Mossy Cobblestone" : "Assets\\Items\\mossy_cobblestone.png",
    "Mossy Cobblestone Slab" : "Assets\\Items\\mossy_cobblestone_slab.png",
    "Mossy Cobblestone Stairs" : "Assets\\Items\\mossy_cobblestone_stairs.png",
    "Mossy Cobblestone Wall" : "Assets\\Items\\mossy_cobblestone_wall.png",
    "Mossy Stone Bricks" : "Assets\\Items\\mossy_stone_bricks.png",
    "Mossy Stone Brick Slab" : "Assets\\Items\\mossy_stone_brick_slab.png",
    "Mossy Stone Brick Stairs" : "Assets\\Items\\mossy_stone_brick_stairs.png",
    "Mossy Stone Brick Wall" : "Assets\\Items\\mossy_stone_brick_wall.png",
    "Mule Spawn Egg" : "Assets\\Items\\mule_spawn_egg.png",
    "Mushroom Stem" : "Assets\\Items\\mushroom_stem.png",
    "Mushroom Stew" : "Assets\\Items\\mushroom_stew.png",
    "Music Disc 11" : "Assets\\Items\\music_disc_11.png",
    "Music Disc 13" : "Assets\\Items\\music_disc_13.png",
    "Music Disc Blocks" : "Assets\\Items\\music_disc_blocks.png",
    "Music Disc Cat" : "Assets\\Items\\music_disc_cat.png",
    "Music Disc Chirp" : "Assets\\Items\\music_disc_chirp.png",
    "Music Disc Far" : "Assets\\Items\\music_disc_far.png",
    "Music Disc Mall" : "Assets\\Items\\music_disc_mall.png",
    "Music Disc Mellohi" : "Assets\\Items\\music_disc_mellohi.png",
    "Music Disc Pigstep" : "Assets\\Items\\music_disc_pigstep.png",
    "Music Disc Stal" : "Assets\\Items\\music_disc_stal.png",
    "Music Disc Strad" : "Assets\\Items\\music_disc_strad.png",
    "Music Disc Wait" : "Assets\\Items\\music_disc_wait.png",
    "Music Disc Ward" : "Assets\\Items\\music_disc_ward.png",
    "Mutton" : "Assets\\Items\\mutton.png",
    "Mycelium" : "Assets\\Items\\mycelium.png",
    "Name Tag" : "Assets\\Items\\name_tag.png",
    "Nautilus Shell" : "Assets\\Items\\nautilus_shell.png",
    "Netherite Axe" : "Assets\\Items\\netherite_axe.png",
    "Netherite Block" : "Assets\\Items\\netherite_block.png",
    "Netherite Boots" : "Assets\\Items\\netherite_boots.png",
    "Netherite Chestplate" : "Assets\\Items\\netherite_chestplate.png",
    "Netherite Helmet" : "Assets\\Items\\netherite_helmet.png",
    "Netherite Hoe" : "Assets\\Items\\netherite_hoe.png",
    "Netherite Ingot" : "Assets\\Items\\netherite_ingot.png",
    "Netherite Leggings" : "Assets\\Items\\netherite_leggings.png",
    "Netherite Pickaxe" : "Assets\\Items\\netherite_pickaxe.png",
    "Netherite Scrap" : "Assets\\Items\\netherite_scrap.png",
    "Netherite Shovel" : "Assets\\Items\\netherite_shovel.png",
    "Netherite Sword" : "Assets\\Items\\netherite_sword.png",
    "Netherrack" : "Assets\\Items\\netherrack.png",
    "Nether Brick" : "Assets\\Items\\nether_brick.png",
    "Nether Bricks" : "Assets\\Items\\nether_bricks.png",
    "Nether Brick Fence" : "Assets\\Items\\nether_brick_fence.png",
    "Nether Brick Slab" : "Assets\\Items\\nether_brick_slab.png",
    "Nether Brick Stairs" : "Assets\\Items\\nether_brick_stairs.png",
    "Nether Brick Wall" : "Assets\\Items\\nether_brick_wall.png",
    "Nether Gold Ore" : "Assets\\Items\\nether_gold_ore.png",
    "Nether Quartz Ore" : "Assets\\Items\\nether_quartz_ore.png",
    "Nether Sprouts" : "Assets\\Items\\nether_sprouts.png",
    "Nether Star" : "Assets\\Items\\nether_star.png",
    "Nether Wart" : "Assets\\Items\\nether_wart.png",
    "Nether Wart Block" : "Assets\\Items\\nether_wart_block.png",
    "Note Block" : "Assets\\Items\\note_block.png",
    "Oak Boat" : "Assets\\Items\\oak_boat.png",
    "Oak Button" : "Assets\\Items\\oak_button.png",
    "Oak Door" : "Assets\\Items\\oak_door.png",
    "Oak Fence" : "Assets\\Items\\oak_fence.png",
    "Oak Fence Gate" : "Assets\\Items\\oak_fence_gate.png",
    "Oak Leaves" : "Assets\\Items\\oak_leaves.png",
    "Oak Log" : "Assets\\Items\\oak_log.png",
    "Oak Planks" : "Assets\\Items\\oak_planks.png",
    "Oak Pressure Plate" : "Assets\\Items\\oak_pressure_plate.png",
    "Oak Sapling" : "Assets\\Items\\oak_sapling.png",
    "Oak Sign" : "Assets\\Items\\oak_sign.png",
    "Oak Slab" : "Assets\\Items\\oak_slab.png",
    "Oak Stairs" : "Assets\\Items\\oak_stairs.png",
    "Oak Trapdoor" : "Assets\\Items\\oak_trapdoor.png",
    "Oak Wood" : "Assets\\Items\\oak_wood.png",
    "Observer" : "Assets\\Items\\observer.png",
    "Obsidian" : "Assets\\Items\\obsidian.png",
    "Ocelot Spawn Egg" : "Assets\\Items\\ocelot_spawn_egg.png",
    "Orange Banner" : "Assets\\Items\\orange_banner.png",
    "Orange Bed" : "Assets\\Items\\orange_bed.png",
    "Orange Carpet" : "Assets\\Items\\orange_carpet.png",
    "Orange Concrete" : "Assets\\Items\\orange_concrete.png",
    "Orange Concrete Powder" : "Assets\\Items\\orange_concrete_powder.png",
    "Orange Dye" : "Assets\\Items\\orange_dye.png",
    "Orange Glazed Terracotta" : "Assets\\Items\\orange_glazed_terracotta.png",
    "Orange Shulker Box" : "Assets\\Items\\orange_shulker_box.png",
    "Orange Stained Glass" : "Assets\\Items\\orange_stained_glass.png",
    "Orange Stained Glass Pane" : "Assets\\Items\\orange_stained_glass_pane.png",
    "Orange Terracotta" : "Assets\\Items\\orange_terracotta.png",
    "Orange Tulip" : "Assets\\Items\\orange_tulip.png",
    "Orange Wool" : "Assets\\Items\\orange_wool.png",
    "Oxeye Daisy" : "Assets\\Items\\oxeye_daisy.png",
    "Packed Ice" : "Assets\\Items\\packed_ice.png",
    "Painting" : "Assets\\Items\\painting.png",
    "Panda Spawn Egg" : "Assets\\Items\\panda_spawn_egg.png",
    "Paper" : "Assets\\Items\\paper.png",
    "Parrot Spawn Egg" : "Assets\\Items\\parrot_spawn_egg.png",
    "Peony" : "Assets\\Items\\peony.png",
    "Petrified Oak Slab" : "Assets\\Items\\petrified_oak_slab.png",
    "Phantom Membrane" : "Assets\\Items\\phantom_membrane.png",
    "Phantom Spawn Egg" : "Assets\\Items\\phantom_spawn_egg.png",
    "Piglin Banner Pattern" : "Assets\\Items\\piglin_banner_pattern.png",
    "Piglin Brute Spawn Egg" : "Assets\\Items\\piglin_brute_spawn_egg.png",
    "Piglin Spawn Egg" : "Assets\\Items\\piglin_spawn_egg.png",
    "Pig Spawn Egg" : "Assets\\Items\\pig_spawn_egg.png",
    "Pillager Spawn Egg" : "Assets\\Items\\pillager_spawn_egg.png",
    "Pink Banner" : "Assets\\Items\\pink_banner.png",
    "Pink Bed" : "Assets\\Items\\pink_bed.png",
    "Pink Carpet" : "Assets\\Items\\pink_carpet.png",
    "Pink Concrete" : "Assets\\Items\\pink_concrete.png",
    "Pink Concrete Powder" : "Assets\\Items\\pink_concrete_powder.png",
    "Pink Dye" : "Assets\\Items\\pink_dye.png",
    "Pink Glazed Terracotta" : "Assets\\Items\\pink_glazed_terracotta.png",
    "Pink Shulker Box" : "Assets\\Items\\pink_shulker_box.png",
    "Pink Stained Glass" : "Assets\\Items\\pink_stained_glass.png",
    "Pink Stained Glass Pane" : "Assets\\Items\\pink_stained_glass_pane.png",
    "Pink Terracotta" : "Assets\\Items\\pink_terracotta.png",
    "Pink Tulip" : "Assets\\Items\\pink_tulip.png",
    "Pink Wool" : "Assets\\Items\\pink_wool.png",
    "Piston" : "Assets\\Items\\piston.png",
    "Player Head" : "Assets\\Items\\player_head.png",
    "Podzol" : "Assets\\Items\\podzol.png",
    "Poisonous Potato" : "Assets\\Items\\poisonous_potato.png",
    "Polar Bear Spawn Egg" : "Assets\\Items\\polar_bear_spawn_egg.png",
    "Polished Andesite" : "Assets\\Items\\polished_andesite.png",
    "Polished Andesite Slab" : "Assets\\Items\\polished_andesite_slab.png",
    "Polished Andesite Stairs" : "Assets\\Items\\polished_andesite_stairs.png",
    "Polished Basalt" : "Assets\\Items\\polished_basalt.png",
    "Polished Blackstone" : "Assets\\Items\\polished_blackstone.png",
    "Polished Blackstone Bricks" : "Assets\\Items\\polished_blackstone_bricks.png",
    "Polished Blackstone Brick Slab" : "Assets\\Items\\polished_blackstone_brick_slab.png",
    "Polished Blackstone Brick Stairs" : "Assets\\Items\\polished_blackstone_brick_stairs.png",
    "Polished Blackstone Brick Wall" : "Assets\\Items\\polished_blackstone_brick_wall.png",
    "Polished Blackstone Button" : "Assets\\Items\\polished_blackstone_button.png",
    "Polished Blackstone Pressure Plate" : "Assets\\Items\\polished_blackstone_pressure_plate.png",
    "Polished Blackstone Slab" : "Assets\\Items\\polished_blackstone_slab.png",
    "Polished Blackstone Stairs" : "Assets\\Items\\polished_blackstone_stairs.png",
    "Polished Blackstone Wall" : "Assets\\Items\\polished_blackstone_wall.png",
    "Polished Diorite" : "Assets\\Items\\polished_diorite.png",
    "Polished Diorite Slab" : "Assets\\Items\\polished_diorite_slab.png",
    "Polished Diorite Stairs" : "Assets\\Items\\polished_diorite_stairs.png",
    "Polished Granite" : "Assets\\Items\\polished_granite.png",
    "Polished Granite Slab" : "Assets\\Items\\polished_granite_slab.png",
    "Polished Granite Stairs" : "Assets\\Items\\polished_granite_stairs.png",
    "Popped Chorus Fruit" : "Assets\\Items\\popped_chorus_fruit.png",
    "Poppy" : "Assets\\Items\\poppy.png",
    "Porkchop" : "Assets\\Items\\porkchop.png",
    "Potato" : "Assets\\Items\\potato.png",
    "Potion of Awkward" : "Assets\\Items\\potion_of_awkward.png",
    "Potion of Fire Resistance" : "Assets\\Items\\potion_of_fire_resistance.png",
    "Potion of Harming" : "Assets\\Items\\potion_of_harming.png",
    "Potion of Healing" : "Assets\\Items\\potion_of_healing.png",
    "Potion of Invisibility" : "Assets\\Items\\potion_of_invisibility.png",
    "Potion of Leaping" : "Assets\\Items\\potion_of_leaping.png",
    "Potion of Long Fire Resistance" : "Assets\\Items\\potion_of_long_fire_resistance.png",
    "Potion of Long Invisibility" : "Assets\\Items\\potion_of_long_invisibility.png",
    "Potion of Long Leaping" : "Assets\\Items\\potion_of_long_leaping.png",
    "Potion of Long Night Vision" : "Assets\\Items\\potion_of_long_night_vision.png",
    "Potion of Long Poison" : "Assets\\Items\\potion_of_long_poison.png",
    "Potion of Long Regeneration" : "Assets\\Items\\potion_of_long_regeneration.png",
    "Potion of Long Slowness" : "Assets\\Items\\potion_of_long_slowness.png",
    "Potion of Long Slow Falling" : "Assets\\Items\\potion_of_long_slow_falling.png",
    "Potion of Long Strength" : "Assets\\Items\\potion_of_long_strength.png",
    "Potion of Long Swiftness" : "Assets\\Items\\potion_of_long_swiftness.png",
    "Potion of Long Turtle Master" : "Assets\\Items\\potion_of_long_turtle_master.png",
    "Potion of Long Water Breathing" : "Assets\\Items\\potion_of_long_water_breathing.png",
    "Potion of Long Weakness" : "Assets\\Items\\potion_of_long_weakness.png",
    "Potion of Luck" : "Assets\\Items\\potion_of_luck.png",
    "Potion of Mundane" : "Assets\\Items\\potion_of_mundane.png",
    "Potion of Night Vision" : "Assets\\Items\\potion_of_night_vision.png",
    "Potion of Poison" : "Assets\\Items\\potion_of_poison.png",
    "Potion of Regeneration" : "Assets\\Items\\potion_of_regeneration.png",
    "Potion of Slowness" : "Assets\\Items\\potion_of_slowness.png",
    "Potion of Slow Falling" : "Assets\\Items\\potion_of_slow_falling.png",
    "Potion of Strength" : "Assets\\Items\\potion_of_strength.png",
    "Potion of Strong Harming" : "Assets\\Items\\potion_of_strong_harming.png",
    "Potion of Strong Healing" : "Assets\\Items\\potion_of_strong_healing.png",
    "Potion of Strong Leaping" : "Assets\\Items\\potion_of_strong_leaping.png",
    "Potion of Strong Poison" : "Assets\\Items\\potion_of_strong_poison.png",
    "Potion of Strong Regeneration" : "Assets\\Items\\potion_of_strong_regeneration.png",
    "Potion of Strong Slowness" : "Assets\\Items\\potion_of_strong_slowness.png",
    "Potion of Strong Strength" : "Assets\\Items\\potion_of_strong_strength.png",
    "Potion of Strong Swiftness" : "Assets\\Items\\potion_of_strong_swiftness.png",
    "Potion of Strong Turtle Master" : "Assets\\Items\\potion_of_strong_turtle_master.png",
    "Potion of Swiftness" : "Assets\\Items\\potion_of_swiftness.png",
    "Potion of Thick" : "Assets\\Items\\potion_of_thick.png",
    "Potion of Turtle Master" : "Assets\\Items\\potion_of_turtle_master.png",
    "Potion of Water" : "Assets\\Items\\potion_of_water.png",
    "Potion of Water Breathing" : "Assets\\Items\\potion_of_water_breathing.png",
    "Potion of Weakness" : "Assets\\Items\\potion_of_weakness.png",
    "Powered Rail" : "Assets\\Items\\powered_rail.png",
    "Prismarine" : "Assets\\Items\\prismarine.png",
    "Prismarine Bricks" : "Assets\\Items\\prismarine_bricks.png",
    "Prismarine Brick Slab" : "Assets\\Items\\prismarine_brick_slab.png",
    "Prismarine Brick Stairs" : "Assets\\Items\\prismarine_brick_stairs.png",
    "Prismarine Crystals" : "Assets\\Items\\prismarine_crystals.png",
    "Prismarine Shard" : "Assets\\Items\\prismarine_shard.png",
    "Prismarine Slab" : "Assets\\Items\\prismarine_slab.png",
    "Prismarine Stairs" : "Assets\\Items\\prismarine_stairs.png",
    "Prismarine Wall" : "Assets\\Items\\prismarine_wall.png",
    "Pufferfish" : "Assets\\Items\\pufferfish.png",
    "Pufferfish Bucket" : "Assets\\Items\\pufferfish_bucket.png",
    "Pufferfish Spawn Egg" : "Assets\\Items\\pufferfish_spawn_egg.png",
    "Pumpkin" : "Assets\\Items\\pumpkin.png",
    "Pumpkin Pie" : "Assets\\Items\\pumpkin_pie.png",
    "Pumpkin Seeds" : "Assets\\Items\\pumpkin_seeds.png",
    "Purple Banner" : "Assets\\Items\\purple_banner.png",
    "Purple Bed" : "Assets\\Items\\purple_bed.png",
    "Purple Carpet" : "Assets\\Items\\purple_carpet.png",
    "Purple Concrete" : "Assets\\Items\\purple_concrete.png",
    "Purple Concrete Powder" : "Assets\\Items\\purple_concrete_powder.png",
    "Purple Dye" : "Assets\\Items\\purple_dye.png",
    "Purple Glazed Terracotta" : "Assets\\Items\\purple_glazed_terracotta.png",
    "Purple Shulker Box" : "Assets\\Items\\purple_shulker_box.png",
    "Purple Stained Glass" : "Assets\\Items\\purple_stained_glass.png",
    "Purple Stained Glass Pane" : "Assets\\Items\\purple_stained_glass_pane.png",
    "Purple Terracotta" : "Assets\\Items\\purple_terracotta.png",
    "Purple Wool" : "Assets\\Items\\purple_wool.png",
    "Purpur Block" : "Assets\\Items\\purpur_block.png",
    "Purpur Pillar" : "Assets\\Items\\purpur_pillar.png",
    "Purpur Slab" : "Assets\\Items\\purpur_slab.png",
    "Purpur Stairs" : "Assets\\Items\\purpur_stairs.png",
    "Quartz" : "Assets\\Items\\quartz.png",
    "Quartz Block" : "Assets\\Items\\quartz_block.png",
    "Quartz Bricks" : "Assets\\Items\\quartz_bricks.png",
    "Quartz Pillar" : "Assets\\Items\\quartz_pillar.png",
    "Quartz Slab" : "Assets\\Items\\quartz_slab.png",
    "Quartz Stairs" : "Assets\\Items\\quartz_stairs.png",
    "Rabbit" : "Assets\\Items\\rabbit.png",
    "Rabbit Foot" : "Assets\\Items\\rabbit_foot.png",
    "Rabbit Hide" : "Assets\\Items\\rabbit_hide.png",
    "Rabbit Spawn Egg" : "Assets\\Items\\rabbit_spawn_egg.png",
    "Rabbit Stew" : "Assets\\Items\\rabbit_stew.png",
    "Rail" : "Assets\\Items\\rail.png",
    "Ravager Spawn Egg" : "Assets\\Items\\ravager_spawn_egg.png",
    "Redstone" : "Assets\\Items\\redstone.png",
    "Redstone Block" : "Assets\\Items\\redstone_block.png",
    "Redstone Lamp" : "Assets\\Items\\redstone_lamp.png",
    "Redstone Ore" : "Assets\\Items\\redstone_ore.png",
    "Redstone Torch" : "Assets\\Items\\redstone_torch.png",
    "Red Banner" : "Assets\\Items\\red_banner.png",
    "Red Bed" : "Assets\\Items\\red_bed.png",
    "Red Carpet" : "Assets\\Items\\red_carpet.png",
    "Red Concrete" : "Assets\\Items\\red_concrete.png",
    "Red Concrete Powder" : "Assets\\Items\\red_concrete_powder.png",
    "Red Dye" : "Assets\\Items\\red_dye.png",
    "Red Glazed Terracotta" : "Assets\\Items\\red_glazed_terracotta.png",
    "Red Mushroom" : "Assets\\Items\\red_mushroom.png",
    "Red Mushroom Block" : "Assets\\Items\\red_mushroom_block.png",
    "Red Nether Bricks" : "Assets\\Items\\red_nether_bricks.png",
    "Red Nether Brick Slab" : "Assets\\Items\\red_nether_brick_slab.png",
    "Red Nether Brick Stairs" : "Assets\\Items\\red_nether_brick_stairs.png",
    "Red Nether Brick Wall" : "Assets\\Items\\red_nether_brick_wall.png",
    "Red Sand" : "Assets\\Items\\red_sand.png",
    "Red Sandstone" : "Assets\\Items\\red_sandstone.png",
    "Red Sandstone Slab" : "Assets\\Items\\red_sandstone_slab.png",
    "Red Sandstone Stairs" : "Assets\\Items\\red_sandstone_stairs.png",
    "Red Sandstone Wall" : "Assets\\Items\\red_sandstone_wall.png",
    "Red Shulker Box" : "Assets\\Items\\red_shulker_box.png",
    "Red Stained Glass" : "Assets\\Items\\red_stained_glass.png",
    "Red Stained Glass Pane" : "Assets\\Items\\red_stained_glass_pane.png",
    "Red Terracotta" : "Assets\\Items\\red_terracotta.png",
    "Red Tulip" : "Assets\\Items\\red_tulip.png",
    "Red Wool" : "Assets\\Items\\red_wool.png",
    "Repeater" : "Assets\\Items\\repeater.png",
    "Respawn Anchor" : "Assets\\Items\\respawn_anchor.png",
    "Rose Bush" : "Assets\\Items\\rose_bush.png",
    "Rotten Flesh" : "Assets\\Items\\rotten_flesh.png",
    "Saddle" : "Assets\\Items\\saddle.png",
    "Salmon" : "Assets\\Items\\salmon.png",
    "Salmon Bucket" : "Assets\\Items\\salmon_bucket.png",
    "Salmon Spawn Egg" : "Assets\\Items\\salmon_spawn_egg.png",
    "Sand" : "Assets\\Items\\sand.png",
    "Sandstone" : "Assets\\Items\\sandstone.png",
    "Sandstone Slab" : "Assets\\Items\\sandstone_slab.png",
    "Sandstone Stairs" : "Assets\\Items\\sandstone_stairs.png",
    "Sandstone Wall" : "Assets\\Items\\sandstone_wall.png",
    "Scaffolding" : "Assets\\Items\\scaffolding.png",
    "Scute" : "Assets\\Items\\scute.png",
    "Seagrass" : "Assets\\Items\\seagrass.png",
    "Sea Lantern" : "Assets\\Items\\sea_lantern.png",
    "Sea Pickle" : "Assets\\Items\\sea_pickle.png",
    "Shears" : "Assets\\Items\\shears.png",
    "Sheep Spawn Egg" : "Assets\\Items\\sheep_spawn_egg.png",
    "Shield" : "Assets\\Items\\shield.png",
    "Shroomlight" : "Assets\\Items\\shroomlight.png",
    "Shulker Box" : "Assets\\Items\\shulker_box.png",
    "Shulker Shell" : "Assets\\Items\\shulker_shell.png",
    "Shulker Spawn Egg" : "Assets\\Items\\shulker_spawn_egg.png",
    "Silverfish Spawn Egg" : "Assets\\Items\\silverfish_spawn_egg.png",
    "Skeleton Horse Spawn Egg" : "Assets\\Items\\skeleton_horse_spawn_egg.png",
    "Skeleton Skull" : "Assets\\Items\\skeleton_skull.png",
    "Skeleton Spawn Egg" : "Assets\\Items\\skeleton_spawn_egg.png",
    "Skull Banner Pattern" : "Assets\\Items\\skull_banner_pattern.png",
    "Slime Ball" : "Assets\\Items\\slime_ball.png",
    "Slime Block" : "Assets\\Items\\slime_block.png",
    "Slime Spawn Egg" : "Assets\\Items\\slime_spawn_egg.png",
    "Smithing Table" : "Assets\\Items\\smithing_table.png",
    "Smoker" : "Assets\\Items\\smoker.png",
    "Smooth Quartz" : "Assets\\Items\\smooth_quartz.png",
    "Smooth Quartz Slab" : "Assets\\Items\\smooth_quartz_slab.png",
    "Smooth Quartz Stairs" : "Assets\\Items\\smooth_quartz_stairs.png",
    "Smooth Red Sandstone" : "Assets\\Items\\smooth_red_sandstone.png",
    "Smooth Red Sandstone Slab" : "Assets\\Items\\smooth_red_sandstone_slab.png",
    "Smooth Red Sandstone Stairs" : "Assets\\Items\\smooth_red_sandstone_stairs.png",
    "Smooth Sandstone" : "Assets\\Items\\smooth_sandstone.png",
    "Smooth Sandstone Slab" : "Assets\\Items\\smooth_sandstone_slab.png",
    "Smooth Sandstone Stairs" : "Assets\\Items\\smooth_sandstone_stairs.png",
    "Smooth Stone" : "Assets\\Items\\smooth_stone.png",
    "Smooth Stone Slab" : "Assets\\Items\\smooth_stone_slab.png",
    "Snow" : "Assets\\Items\\snow.png",
    "Snowball" : "Assets\\Items\\snowball.png",
    "Snow Block" : "Assets\\Items\\snow_block.png",
    "Soul Campfire" : "Assets\\Items\\soul_campfire.png",
    "Soul Lantern" : "Assets\\Items\\soul_lantern.png",
    "Soul Sand" : "Assets\\Items\\soul_sand.png",
    "Soul Soil" : "Assets\\Items\\soul_soil.png",
    "Soul Torch" : "Assets\\Items\\soul_torch.png",
    "Spectral Arrow" : "Assets\\Items\\spectral_arrow.png",
    "Spider Eye" : "Assets\\Items\\spider_eye.png",
    "Spider Spawn Egg" : "Assets\\Items\\spider_spawn_egg.png",
    "Splash Potion of Awkward" : "Assets\\Items\\splash_potion_of_awkward.png",
    "Splash Potion of Fire Resistance" : "Assets\\Items\\splash_potion_of_fire_resistance.png",
    "Splash Potion of Harming" : "Assets\\Items\\splash_potion_of_harming.png",
    "Splash Potion of Healing" : "Assets\\Items\\splash_potion_of_healing.png",
    "Splash Potion of Invisibility" : "Assets\\Items\\splash_potion_of_invisibility.png",
    "Splash Potion of Leaping" : "Assets\\Items\\splash_potion_of_leaping.png",
    "Splash Potion of Long Fire Resistance" : "Assets\\Items\\splash_potion_of_long_fire_resistance.png",
    "Splash Potion of Long Invisibility" : "Assets\\Items\\splash_potion_of_long_invisibility.png",
    "Splash Potion of Long Leaping" : "Assets\\Items\\splash_potion_of_long_leaping.png",
    "Splash Potion of Long Night Vision" : "Assets\\Items\\splash_potion_of_long_night_vision.png",
    "Splash Potion of Long Poison" : "Assets\\Items\\splash_potion_of_long_poison.png",
    "Splash Potion of Long Regeneration" : "Assets\\Items\\splash_potion_of_long_regeneration.png",
    "Splash Potion of Long Slowness" : "Assets\\Items\\splash_potion_of_long_slowness.png",
    "Splash Potion of Long Slow Falling" : "Assets\\Items\\splash_potion_of_long_slow_falling.png",
    "Splash Potion of Long Strength" : "Assets\\Items\\splash_potion_of_long_strength.png",
    "Splash Potion of Long Swiftness" : "Assets\\Items\\splash_potion_of_long_swiftness.png",
    "Splash Potion of Long Turtle Master" : "Assets\\Items\\splash_potion_of_long_turtle_master.png",
    "Splash Potion of Long Water Breathing" : "Assets\\Items\\splash_potion_of_long_water_breathing.png",
    "Splash Potion of Long Weakness" : "Assets\\Items\\splash_potion_of_long_weakness.png",
    "Splash Potion of Luck" : "Assets\\Items\\splash_potion_of_luck.png",
    "Splash Potion of Mundane" : "Assets\\Items\\splash_potion_of_mundane.png",
    "Splash Potion of Night Vision" : "Assets\\Items\\splash_potion_of_night_vision.png",
    "Splash Potion of Poison" : "Assets\\Items\\splash_potion_of_poison.png",
    "Splash Potion of Regeneration" : "Assets\\Items\\splash_potion_of_regeneration.png",
    "Splash Potion of Slowness" : "Assets\\Items\\splash_potion_of_slowness.png",
    "Splash Potion of Slow Falling" : "Assets\\Items\\splash_potion_of_slow_falling.png",
    "Splash Potion of Strength" : "Assets\\Items\\splash_potion_of_strength.png",
    "Splash Potion of Strong Harming" : "Assets\\Items\\splash_potion_of_strong_harming.png",
    "Splash Potion of Strong Healing" : "Assets\\Items\\splash_potion_of_strong_healing.png",
    "Splash Potion of Strong Leaping" : "Assets\\Items\\splash_potion_of_strong_leaping.png",
    "Splash Potion of Strong Poison" : "Assets\\Items\\splash_potion_of_strong_poison.png",
    "Splash Potion of Strong Regeneration" : "Assets\\Items\\splash_potion_of_strong_regeneration.png",
    "Splash Potion of Strong Slowness" : "Assets\\Items\\splash_potion_of_strong_slowness.png",
    "Splash Potion of Strong Strength" : "Assets\\Items\\splash_potion_of_strong_strength.png",
    "Splash Potion of Strong Swiftness" : "Assets\\Items\\splash_potion_of_strong_swiftness.png",
    "Splash Potion of Strong Turtle Master" : "Assets\\Items\\splash_potion_of_strong_turtle_master.png",
    "Splash Potion of Swiftness" : "Assets\\Items\\splash_potion_of_swiftness.png",
    "Splash Potion of Thick" : "Assets\\Items\\splash_potion_of_thick.png",
    "Splash Potion of Turtle Master" : "Assets\\Items\\splash_potion_of_turtle_master.png",
    "Splash Potion of Water" : "Assets\\Items\\splash_potion_of_water.png",
    "Splash Potion of Water Breathing" : "Assets\\Items\\splash_potion_of_water_breathing.png",
    "Splash Potion of Weakness" : "Assets\\Items\\splash_potion_of_weakness.png",
    "Sponge" : "Assets\\Items\\sponge.png",
    "Spruce Boat" : "Assets\\Items\\spruce_boat.png",
    "Spruce Button" : "Assets\\Items\\spruce_button.png",
    "Spruce Door" : "Assets\\Items\\spruce_door.png",
    "Spruce Fence" : "Assets\\Items\\spruce_fence.png",
    "Spruce Fence Gate" : "Assets\\Items\\spruce_fence_gate.png",
    "Spruce Leaves" : "Assets\\Items\\spruce_leaves.png",
    "Spruce Log" : "Assets\\Items\\spruce_log.png",
    "Spruce Planks" : "Assets\\Items\\spruce_planks.png",
    "Spruce Pressure Plate" : "Assets\\Items\\spruce_pressure_plate.png",
    "Spruce Sapling" : "Assets\\Items\\spruce_sapling.png",
    "Spruce Sign" : "Assets\\Items\\spruce_sign.png",
    "Spruce Slab" : "Assets\\Items\\spruce_slab.png",
    "Spruce Stairs" : "Assets\\Items\\spruce_stairs.png",
    "Spruce Trapdoor" : "Assets\\Items\\spruce_trapdoor.png",
    "Spruce Wood" : "Assets\\Items\\spruce_wood.png",
    "Squid Spawn Egg" : "Assets\\Items\\squid_spawn_egg.png",
    "Stick" : "Assets\\Items\\stick.png",
    "Sticky Piston" : "Assets\\Items\\sticky_piston.png",
    "Stone" : "Assets\\Items\\stone.png",
    "Stonecutter" : "Assets\\Items\\stonecutter.png",
    "Stone Axe" : "Assets\\Items\\stone_axe.png",
    "Stone Bricks" : "Assets\\Items\\stone_bricks.png",
    "Stone Brick Slab" : "Assets\\Items\\stone_brick_slab.png",
    "Stone Brick Stairs" : "Assets\\Items\\stone_brick_stairs.png",
    "Stone Brick Wall" : "Assets\\Items\\stone_brick_wall.png",
    "Stone Button" : "Assets\\Items\\stone_button.png",
    "Stone Hoe" : "Assets\\Items\\stone_hoe.png",
    "Stone Pickaxe" : "Assets\\Items\\stone_pickaxe.png",
    "Stone Pressure Plate" : "Assets\\Items\\stone_pressure_plate.png",
    "Stone Shovel" : "Assets\\Items\\stone_shovel.png",
    "Stone Slab" : "Assets\\Items\\stone_slab.png",
    "Stone Stairs" : "Assets\\Items\\stone_stairs.png",
    "Stone Sword" : "Assets\\Items\\stone_sword.png",
    "Stray Spawn Egg" : "Assets\\Items\\stray_spawn_egg.png",
    "Strider Spawn Egg" : "Assets\\Items\\strider_spawn_egg.png",
    "String" : "Assets\\Items\\string.png",
    "Stripped Acacia Log" : "Assets\\Items\\stripped_acacia_log.png",
    "Stripped Acacia Wood" : "Assets\\Items\\stripped_acacia_wood.png",
    "Stripped Birch Log" : "Assets\\Items\\stripped_birch_log.png",
    "Stripped Birch Wood" : "Assets\\Items\\stripped_birch_wood.png",
    "Stripped Crimson Hyphae" : "Assets\\Items\\stripped_crimson_hyphae.png",
    "Stripped Crimson Stem" : "Assets\\Items\\stripped_crimson_stem.png",
    "Stripped Dark Oak Log" : "Assets\\Items\\stripped_dark_oak_log.png",
    "Stripped Dark Oak Wood" : "Assets\\Items\\stripped_dark_oak_wood.png",
    "Stripped Jungle Log" : "Assets\\Items\\stripped_jungle_log.png",
    "Stripped Jungle Wood" : "Assets\\Items\\stripped_jungle_wood.png",
    "Stripped Oak Log" : "Assets\\Items\\stripped_oak_log.png",
    "Stripped Oak Wood" : "Assets\\Items\\stripped_oak_wood.png",
    "Stripped Spruce Log" : "Assets\\Items\\stripped_spruce_log.png",
    "Stripped Spruce Wood" : "Assets\\Items\\stripped_spruce_wood.png",
    "Stripped Warped Hyphae" : "Assets\\Items\\stripped_warped_hyphae.png",
    "Stripped Warped Stem" : "Assets\\Items\\stripped_warped_stem.png",
    "Sugar" : "Assets\\Items\\sugar.png",
    "Sugar Cane" : "Assets\\Items\\sugar_cane.png",
    "Sunflower" : "Assets\\Items\\sunflower.png",
    "Sweet Berries" : "Assets\\Items\\sweet_berries.png",
    "Tall Grass" : "Assets\\Items\\tall_grass.png",
    "Target" : "Assets\\Items\\target.png",
    "Terracotta" : "Assets\\Items\\terracotta.png",
    "Tnt" : "Assets\\Items\\tnt.png",
    "Tnt Minecart" : "Assets\\Items\\tnt_minecart.png",
    "Torch" : "Assets\\Items\\torch.png",
    "Totem of Undying" : "Assets\\Items\\totem_of_undying.png",
    "Trader Llama Spawn Egg" : "Assets\\Items\\trader_llama_spawn_egg.png",
    "Trapped Chest" : "Assets\\Items\\trapped_chest.png",
    "Trident" : "Assets\\Items\\trident.png",
    "Tripwire Hook" : "Assets\\Items\\tripwire_hook.png",
    "Tropical Fish" : "Assets\\Items\\tropical_fish.png",
    "Tropical Fish Bucket" : "Assets\\Items\\tropical_fish_bucket.png",
    "Tropical Fish Spawn Egg" : "Assets\\Items\\tropical_fish_spawn_egg.png",
    "Tube Coral" : "Assets\\Items\\tube_coral.png",
    "Tube Coral Block" : "Assets\\Items\\tube_coral_block.png",
    "Tube Coral Fan" : "Assets\\Items\\tube_coral_fan.png",
    "Turtle Egg" : "Assets\\Items\\turtle_egg.png",
    "Turtle Helmet" : "Assets\\Items\\turtle_helmet.png",
    "Turtle Spawn Egg" : "Assets\\Items\\turtle_spawn_egg.png",
    "Twisting Vines" : "Assets\\Items\\twisting_vines.png",
    "Vex Spawn Egg" : "Assets\\Items\\vex_spawn_egg.png",
    "Villager Spawn Egg" : "Assets\\Items\\villager_spawn_egg.png",
    "Vindicator Spawn Egg" : "Assets\\Items\\vindicator_spawn_egg.png",
    "Vine" : "Assets\\Items\\vine.png",
    "Wandering Trader Spawn Egg" : "Assets\\Items\\wandering_trader_spawn_egg.png",
    "Warped Button" : "Assets\\Items\\warped_button.png",
    "Warped Door" : "Assets\\Items\\warped_door.png",
    "Warped Fence" : "Assets\\Items\\warped_fence.png",
    "Warped Fence Gate" : "Assets\\Items\\warped_fence_gate.png",
    "Warped Fungus" : "Assets\\Items\\warped_fungus.png",
    "Warped Fungus On A Stick" : "Assets\\Items\\warped_fungus_on_a_stick.png",
    "Warped Hyphae" : "Assets\\Items\\warped_hyphae.png",
    "Warped Nylium" : "Assets\\Items\\warped_nylium.png",
    "Warped Planks" : "Assets\\Items\\warped_planks.png",
    "Warped Pressure Plate" : "Assets\\Items\\warped_pressure_plate.png",
    "Warped Roots" : "Assets\\Items\\warped_roots.png",
    "Warped Sign" : "Assets\\Items\\warped_sign.png",
    "Warped Slab" : "Assets\\Items\\warped_slab.png",
    "Warped Stairs" : "Assets\\Items\\warped_stairs.png",
    "Warped Stem" : "Assets\\Items\\warped_stem.png",
    "Warped Trapdoor" : "Assets\\Items\\warped_trapdoor.png",
    "Warped Wart Block" : "Assets\\Items\\warped_wart_block.png",
    "Water Bucket" : "Assets\\Items\\water_bucket.png",
    "Weeping Vines" : "Assets\\Items\\weeping_vines.png",
    "Wet Sponge" : "Assets\\Items\\wet_sponge.png",
    "Wheat" : "Assets\\Items\\wheat.png",
    "Wheat Seeds" : "Assets\\Items\\wheat_seeds.png",
    "White Banner" : "Assets\\Items\\white_banner.png",
    "White Bed" : "Assets\\Items\\white_bed.png",
    "White Carpet" : "Assets\\Items\\white_carpet.png",
    "White Concrete" : "Assets\\Items\\white_concrete.png",
    "White Concrete Powder" : "Assets\\Items\\white_concrete_powder.png",
    "White Dye" : "Assets\\Items\\white_dye.png",
    "White Glazed Terracotta" : "Assets\\Items\\white_glazed_terracotta.png",
    "White Shulker Box" : "Assets\\Items\\white_shulker_box.png",
    "White Stained Glass" : "Assets\\Items\\white_stained_glass.png",
    "White Stained Glass Pane" : "Assets\\Items\\white_stained_glass_pane.png",
    "White Terracotta" : "Assets\\Items\\white_terracotta.png",
    "White Tulip" : "Assets\\Items\\white_tulip.png",
    "White Wool" : "Assets\\Items\\white_wool.png",
    "Witch Spawn Egg" : "Assets\\Items\\witch_spawn_egg.png",
    "Wither Rose" : "Assets\\Items\\wither_rose.png",
    "Wither Skeleton Skull" : "Assets\\Items\\wither_skeleton_skull.png",
    "Wither Skeleton Spawn Egg" : "Assets\\Items\\wither_skeleton_spawn_egg.png",
    "Wolf Spawn Egg" : "Assets\\Items\\wolf_spawn_egg.png",
    "Wooden Axe" : "Assets\\Items\\wooden_axe.png",
    "Wooden Hoe" : "Assets\\Items\\wooden_hoe.png",
    "Wooden Pickaxe" : "Assets\\Items\\wooden_pickaxe.png",
    "Wooden Shovel" : "Assets\\Items\\wooden_shovel.png",
    "Wooden Sword" : "Assets\\Items\\wooden_sword.png",
    "Writable Book" : "Assets\\Items\\writable_book.png",
    "Yellow Banner" : "Assets\\Items\\yellow_banner.png",
    "Yellow Bed" : "Assets\\Items\\yellow_bed.png",
    "Yellow Carpet" : "Assets\\Items\\yellow_carpet.png",
    "Yellow Concrete" : "Assets\\Items\\yellow_concrete.png",
    "Yellow Concrete Powder" : "Assets\\Items\\yellow_concrete_powder.png",
    "Yellow Dye" : "Assets\\Items\\yellow_dye.png",
    "Yellow Glazed Terracotta" : "Assets\\Items\\yellow_glazed_terracotta.png",
    "Yellow Shulker Box" : "Assets\\Items\\yellow_shulker_box.png",
    "Yellow Stained Glass" : "Assets\\Items\\yellow_stained_glass.png",
    "Yellow Stained Glass Pane" : "Assets\\Items\\yellow_stained_glass_pane.png",
    "Yellow Terracotta" : "Assets\\Items\\yellow_terracotta.png",
    "Yellow Wool" : "Assets\\Items\\yellow_wool.png",
    "Zoglin Spawn Egg" : "Assets\\Items\\zoglin_spawn_egg.png",
    "Zombie Head" : "Assets\\Items\\zombie_head.png",
    "Zombie Horse Spawn Egg" : "Assets\\Items\\zombie_horse_spawn_egg.png",
    "Zombie Spawn Egg" : "Assets\\Items\\zombie_spawn_egg.png",
    "Zombie Villager Spawn Egg" : "Assets\\Items\\zombie_villager_spawn_egg.png",
    "Zombified Piglin Spawn Egg" : "Assets\\Items\\zombified_piglin_spawn_egg.png",
}